### ISSUE TITLE
Release 1.8 launch date

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1039]
I plan to fix a few things before releasing 1.8:

* DHCP on Linux (#1038)
* Bugs (#1037)
* (maybe) consistent configurable search paths (#1027)
* (optionally) fixed "netlab status" (#1008)

Hopefully I can get that done to have 1.8 ready for March 1st (or so). Anything else you'd like to see in that release @jbemmel @ssasso?

**Comment by ssasso** [comment]
I won't be able to work on anything here for the next two weeks, so for me you can go with 1.8

**Comment by ipspace** [comment]
The release notes are ready, will wait until March 1st before pushing out the release in case some other regression bugs pop up (with advance apologies to @ssasso)
