### ISSUE TITLE
Rewrite 'netlab status' to show data focused on current lab instance

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1044]
When running in multilab mode (but also if other docker images are running), the output of ```netlab status``` is cluttered with images not relevant to the lab we're interested in.

Since there already is an assumption of having the netlab state info available in the working directory, I propose we use that to filter the output of netlab status by default to only include the current lab nodes.

What I'm not aware of, is whether this can also be reused for non-clab backends. I'm just now noticing the ```instance``` parameter to the netlab CLI, will look into that.

_Originally posted by @sdktr in https://github.com/ipspace/netlab/discussions/1008_

**Comment by ipspace** [comment]
In any case, we need:

* Something to display the current instance in a way @sdktr likes ;)
* Something to display all running instances (so we don't have to chase them around)
* Something to display the instance startup log in case we have to do troubleshooting
* A cleanup/reset command

How about this:

* **netlab status** shows the summary of the current lab instance + workloads or tells you there's no lab running in the current directory. An optional '--instance' parameter allows you to specify an instance
* **netlab status --log** displays the log of the current or specified instance
* **netlab status --global** displays all lab instances but not per-instance workloads
* **netlab status --workload** displays all running virtual machines and containers
* **netlab status --shutdown** shuts down up a lab instance (so you don't have to chdir there and execute **netlab down**)
* **netlab status --reset** deletes the lab tracking information in case it got corrupted

Alternative suggestions are most welcome, I'm a bit stuck /cc @sdktr @jbemmel @ssasso @steffann

**Comment by ipspace** [comment]
@sdktr: The rewritten code is ready in the "status" branch. Any feedback would be highly appreciated. Will wait a week or so before merging it.

**Comment by sdargoeuves** [comment]
@ipspace I really like the new output of the `netlab status` from the `status` branch. But I haven't been able to use the `--all` option:

```
~/c/netlab/labs/arista-ospf ❯ /home/seb/code/netlab/netlab/netlab status --all      seb@linux-lab 12:37:32
Active lab instance(s)

Traceback (most recent call last):
  File "/home/seb/code/netlab/netlab/netlab", line 12, in <module>
    netsim.cli.lab_commands(__file__)
  File "/home/seb/code/netlab/netlab/netsim/cli/__init__.py", line 273, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/seb/code/netlab/netlab/netsim/cli/status.py", line 233, in run
    display_active_labs(topology,args,lab_states)
  File "/home/seb/code/netlab/netlab/netsim/cli/status.py", line 86, in display_active_labs
    strings.print_table(heading,rows)
  File "/home/seb/code/netlab/netlab/netsim/utils/strings.py", line 152, in print_table
    table.add_row(*r)
  File "/usr/local/lib/python3.10/dist-packages/rich/table.py", line 460, in add_row
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: unable to render int; a string or other renderable object is required
~/c/netlab/labs/arista-ospf ❯ /home/seb/code/netlab/netlab/netlab status            seb@linux-lab 12:37:37
Lab 2 in /home/seb/code/netlab/labs/arista-ospf
  status: started
  provider(s): libvirt

┏━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┓
┃ node ┃ device ┃ image       ┃ mgmt IPv4     ┃ connection  ┃ provider ┃ VM/container ┃ status  ┃
┡━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━┩
│ r1   │ eos    │ arista/veos │ 10.194.56.179 │ network_cli │ libvirt  │ ml_2_r1      │ running │
├──────┼────────┼─────────────┼───────────────┼─────────────┼──────────┼──────────────┼─────────┤
│ r2   │ eos    │ arista/veos │ 10.194.56.180 │ network_cli │ libvirt  │ ml_2_r2      │ running │
├──────┼────────┼─────────────┼───────────────┼─────────────┼──────────┼──────────────┼─────────┤
│ r3   │ eos    │ arista/veos │ 10.194.56.181 │ network_cli │ libvirt  │ ml_2_r3      │ running │
└──────┴────────┴─────────────┴───────────────┴─────────────┴──────────┴──────────────┴─────────┘
~/code/netlab/labs/arista-ospf ❯
```
