### ISSUE TITLE
[BUG] Error in connect string /cli/connect.py

### ISSUE THREAD

**Issue by paulkoan** [ipspace/netlab#1055]
### Describe the bug

This is the connect args in netlab/cli/connect.py:

`c_args = ['ssh','-o','UserKnownHostsFile=/dev/null','-o','StrictHostKeyChecking=no','-o','LogLevel ERROR']`

This fails because it is missing an equals sign, and should read:

`c_args = ['ssh','-o','UserKnownHostsFile=/dev/null','-o','StrictHostKeyChecking=no','-o','LogLevel=ERROR']`

### To Reproduce

`pip install networklab` 

(version 1.8 at time of writing). Start one of the labs after basic/0
Use FRR as router

```
cd basic/1-session
netlab up
netlab connect rtr

```

### Expected behavior

The ssh session should start, but instead it drops back to the prompt without error.  Manually executing the command works fine:

`ssh admin@clab-session-rtr -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR`

### Lab topology

```
basic/1-session with FRR as default router
```

### Output

```
Please add the output you get when running `netlab create` on the minimum lab topology provided
```
The output is all correct.

### Version

netlab version 1.8.0

### Additional context

Sorry not sure how to do a PR

**Comment by ipspace** [comment]
Thanks a million for reporting this. Fixed, will push out 1.8.0-post1 later today.

We've been using the current code "forever"; the behavior you observed was probably triggered by a "recent" (for whatever value of "recent") fix in OpenSSH. Could you please check your OpenSSH version with `ssh -V` and post it here? Thank you!

**Comment by paulkoan** [comment]
Yep it is `OpenSSH_9.6p1 Debian-3, OpenSSL 3.1.4 24 Oct 2023`

**Comment by ipspace** [comment]
> Yep it is `OpenSSH_9.6p1 Debian-3, OpenSSL 3.1.4 24 Oct 2023`

That explains it. Ubuntu 22.04 is still at `OpenSSH_8.9p1 Ubuntu-3ubuntu0.6, OpenSSL 3.0.2 15 Mar 2022`

Thanks again, Ivan

**Comment by ipspace** [comment]
> Thanks a million for reporting this. Fixed, will push out 1.8.0-post1 later today.

1.8.0-post1 is out ;)

**Comment by paulkoan** [comment]
Well that is weird:
```
┌──(paul㉿nova)-[~/clab/bgplab/basic/4-ipv6]
└─$ netlab connect rtr
Connecting to clab-ipv6-rtr using SSH port 22

┌──(paul㉿nova)-[~/clab/bgplab/basic/4-ipv6]
└─$ netlab connect rtr  --dry-run
DRY RUN: ['sshpass', '-p', 'admin', 'ssh', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'LogLevel=ERROR', 'admin@clab-ipv6-rtr']
```
The issue with the args is fixed, but it still doesn't connect

**Comment by paulkoan** [comment]
Oh crap ignore this, I didn't have sshpass installed
