### ISSUE TITLE
[BUG] Missing BGP cluster ID on VyOS

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1063]
Based on https://netlab-cicd.pages.dev/vyos/libvirt/bgp/03-ibgp-rr.yml-validate.log, it seems like VyOS BGP template does not configure cluster ID on BGP route reflectors

Lab topology @ https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/03-ibgp-rr.yml

**Comment by ssasso** [comment]
@ipspace most probably it's me missing something, but maybe you already encountered this.

taking the lab topology linked above, with the latest dev branch, I have:

```
root@hippo:~/TOPOLOGIES/autotesting/03ibgprr# netlab create -p clab -d vyos
[ERRORS]  Errors found in topology.yml
[TYPE]    topology: attribute name must be a 16-character identifier, found str
[HINT]    FYI: a 16-character identifier is a string containing up to 16 alphanumeric characters, numbers and underscores
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

**Comment by ssasso** [comment]
Well, I renamed the directory to something shorter to make it work ;)

**Comment by ipspace** [comment]
An identifier has to start with a letter or underscore, not a number. The requirement is there because we're using topology name for all sorts of things like VM names or Linux bridge names, and I don't want to deal with who-supports-what nightmare.

The error message should be better, will fix.
