### ISSUE TITLE
[BUG] VyOS: Inter-VRF route leaking doesn't work in simple scenarios

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1067]
Multiple "common services" VRF scenarios fail with VyOS, the only one that succeeds is the one running BGP with the CE-router.

It could be that (like many other platforms) VyOS requires BGP to be configured the moment you want to do inter-VRF route leaking.

Summary @ https://netlab-cicd.pages.dev/_html/vyos-libvirt-vrf (scenarios 31, 32, 33)

**Comment by ssasso** [comment]
Yes, BGP is required for inter-VRF leaking.
How did you solve this "testing" for other vendors? Can you please point me to an example?

**Comment by ssasso** [comment]
(of course changing the test file and adding

```
  routers:
    members: [ dut ]
    module: [ vrf,bgp ]
    bgp.as: 65000
```

makes the test to pass:

```
[red]     h1 trying to reach srv [ node(s): h1 ]
[PASS]    h1: Ping to srv succeeded
[PASS]    Test succeeded

[blue]    h2 trying to reach srv [ node(s): h2 ]
[PASS]    h2: Ping to srv succeeded
[PASS]    Test succeeded

[s2s]     h1 should not be able to reach h2 [ node(s): h1 ]
[PASS]    h1: Ping to h2 failed as expected
[PASS]    Test succeeded

[SUCCESS] Tests passed: 3
```

**Comment by ipspace** [comment]
When the topology requires inter-VRF leaking, **bgp.as** is set for the node even though the BGP module is not active. You can use the "is **bgp.as** set" test in VRF configuration template to configure BGP. That's what I'm doing in Arista EOS and Cisco IOS templates.

**Comment by ssasso** [comment]
> When the topology requires inter-VRF leaking, **bgp.as** is set for the node even though the BGP module is not active. You can use the "is **bgp.as** set" test in VRF configuration template to configure BGP. That's what I'm doing in Arista EOS and Cisco IOS templates.

That's what I am already doing: https://github.com/ssasso/netlab/blob/d14aef7b1f93d2fe3de7580068e2cd19d4b138c1/netsim/ansible/templates/vrf/vyos.j2#L15

So I need to deep dive further into this.

**Comment by ipspace** [comment]
Maybe you have to configure global BGP before the VRF BGP configuration takes effect. That would explain why your configuration works when the BGP module is added.

In EOS and IOS cases, you cannot get to the VRF AF without starting the global BGP process first.

**Comment by ssasso** [comment]
You're right, as always ;)

**Comment by ipspace** [comment]
> You're right, as always ;)

Sometimes I'd love to be wrong (in particular when I predict bad things will happen...).

Anyway, so nice that you fixed all those minor details. Do you feel like you want to tackle the one remaining BGP issue (large community propagation)?

**Comment by ssasso** [comment]
> Do you feel like you want to tackle the one remaining BGP issue (large community propagation)?

yep, do you have an issue description? or point me to the right test case and I will try to run it
