### ISSUE TITLE
[BUG] SR Linux does not advertise loopback prefix into BGP

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1069]
Based on https://netlab-cicd.pages.dev/srlinux/clab/bgp/04-originate.yml-validate.log, it seems that SR Linux (under some circumstances?) does not add its loopback address into the BGP table even when the **bgp.advertise_loopback** is set to True.

The device that does not originate its loopback prefix in BGP is a standalone router with a single EBGP session, which makes it even more intriguing.

Topology @ https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/04-originate.yml

**Comment by jbemmel** [comment]
I am able to run that test case and it validates eventually. I did notice a delay, not sure where that is coming from

**Comment by ipspace** [comment]
I had to tweak numerous BGP timers on Cisco IOS to get it to originate prefixes in reasonable time. No such problems on most other platforms.

It is interesting, though, that the prefix specified in the **bgp.originate** attribute gets advertised pretty quickly while the one configured on the loopback interface is not.

**Comment by jbemmel** [comment]
Test passes for me now
