### ISSUE TITLE
[BUG] SR Linux does not start an interface (unnumbered) EBGP session on IPv4 unnumbered interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1070]
In the test topology https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/06-unnumbered.yml the EBGP sessions across unnumbered IPv4 interfaces are not established (validation log @ https://netlab-cicd.pages.dev/srlinux/clab/bgp/06-unnumbered.yml-validate.log)

It could be that SR Linux configuration templates require **ipv6: true** to be set together with **ipv4: true** for EBGP sessions to work. If that's the case, we have to either fix the template or add a device quirk to set **ipv6: true** on SR Linux interfaces with unnumbered EBGP sessions.

@jbemmel Please let me know which fix you'd like to see implemented. I can add the device quirk if needed.

**Comment by jbemmel** [comment]
IPv4 unnumbered is a recent addition, the templates need to be updated to configure it correctly. I’ll take a lookSent from my iPhoneOn Apr 9, 2024, at 11:46 AM, Ivan Pepelnjak ***@***.***> wrote:﻿
In the test topology https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/06-unnumbered.yml the EBGP sessions across unnumbered IPv4 interfaces are not established (validation log @ https://netlab-cicd.pages.dev/srlinux/clab/bgp/06-unnumbered.yml-validate.log)
It could be that SR Linux configuration templates require ipv6: true to be set together with ipv4: true for EBGP sessions to work. If that's the case, we have to either fix the template or add a device quirk to set ipv6: true on SR Linux interfaces with unnumbered EBGP sessions.
@jbemmel Please let me know which fix you'd like to see implemented. I can add the device quirk if needed.

**Comment by ipspace** [comment]
I know you got unnumbered EBGP sessions working, and IPv4 AF running over it with RFC 8950, but I don't remember what you did to get that to work.

Anyway, I checked the resulting data model for the 06-unnumbered topology, and _netlab_ already sets **ipv6: true** on unnumbered IPv4 interfaces that run EBGP, so there's no need to set that. 

However, in the resulting SR Linux configuration, you don't configure X1 and X2 as the neighbors (only X3 is configured), probably because you're checking that **ipv6** must be set to **True** on the neighbor, not just on the interface. Looks like that's all that needs to be fixed?
