### ISSUE TITLE
[BUG] vagrant-libvirt create_box.sh script creates invalid box metadata

### ISSUE THREAD

**Issue by jotasantos** [ipspace/netlab#1089]
### Describe the bug

When I try to add a vagrant box I get the following error. I have tested with multiple vEOS and CSR versions:
... content removed, full version in attached file 'full-outputs.txt' ...
==> box: Loading metadata for box 'box.json'
    box: URL: file:///tmp/veos/box.json
==> box: Adding box 'arista/veos' (v4.31.2F) for provider: libvirt
    box: Unpacking necessary files from: file:///tmp/veos/eos.box
The metadata associated with the box 'arista/veos' appears corrupted. <<<<<<<<<<<<<<<<<<<
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.
Error executing vagrant box add box.json:
  Command '['vagrant', 'box', 'add', 'box.json']' returned non-zero exit status 1.

### To Reproduce
- Fresh ubuntu 22.04.4 LTS vm installation. 61440Mb and 10cpu
- Netlab installed with the following commands without errors:
sudo apt-get update
sudo apt-get install -y python3-pip
sudo pip3 install --ignore-installed networklab
sudo pip3 install --upgrade pyopenssl cryptography
netlab install -y ubuntu ansible libvirt containerlab

sudo usermod -aG libvirt $(whoami)
sudo usermod -aG docker $(whoami)

####  my user is in both libvirt and libvirt groups
groups jaime
jaime : jaime adm cdrom sudo dip plugdev lpadmin lxd sambashare libvirt docker

#####  vagrant and libvirt versions
vagrant version
Installed Version: 2.4.0
Latest Version: 2.4.1

##### When I try to add a vagrant box I get the following error. I have tested with multiple vEOS and CSR versions:
... content removed, full version in attached file 'full-outputs.txt' ...
Importing Vagrant box

==> box: Loading metadata for box 'box.json'
    box: URL: file:///tmp/veos/box.json
==> box: Adding box 'arista/veos' (v4.31.2F) for provider: libvirt
    box: Unpacking necessary files from: file:///tmp/veos/eos.box
The metadata associated with the box 'arista/veos' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.
Error executing vagrant box add box.json:
  Command '['vagrant', 'box', 'add', 'box.json']' returned non-zero exit status 1.
Failed to add Vagrant box. Fix the error(s) and use "vagrant box add box.json" to add it.

### Expected behavior

The vagrant box should be added and appear when doing 'vagrant box list'

### Version

netlab version
netlab version 1.8.1

### Additional context

I attach file with: 
- contents of the folder post install error. 
- 'cat' and jq of relevant files
-  vagrant debug output

[full-outputs.txt](https://github.com/ipspace/netlab/files/14964650/full-outputs.txt)

[vagrant-debug.txt](https://github.com/ipspace/netlab/files/14964651/vagrant-debug.txt)

**Comment by ipspace** [comment]
First of all, thanks a million for such a detailed error report!

I checked my installation, and the contents of box.json and metadata.json are identical to yours (apart from the folder name). Now we have to chase down what changed behind the scenes. What vagrant version are you using?

**Comment by ipspace** [comment]
Also (based on https://stackoverflow.com/questions/30347843/vagrant-meta-data-is-corrupt), what Python version are you using? Could you attach the results for `hexdump box.json` and `hexdump metadata.json`?

**Comment by ipspace** [comment]
> What vagrant version are you using?

Oops, forget about this one. Found the information in your error report. Will try to reproduce the problem...

**Comment by ipspace** [comment]
Update: It worked for me, starting with a fresh VM but admittedly with 4.28.3M. I have no idea what's going on.

**Comment by jotasantos** [comment]
Thanks for the update!. Will try later on with your veos version. Python
is 3.10. Can you tell me which exact Ubuntu version you are using?

**Comment by ipspace** [comment]
> Thanks for the update!. Will try later on with your veos version.

That shouldn't matter as you get the same problem with CSR boxes.

> Python is 3.10.

Same here.

> Can you tell me which exact Ubuntu version you are using?

I ran the test on a Ubuntu VM started from this box: https://app.vagrantup.com/generic/boxes/ubuntu2204, and **apt-get upgrade** did not upgrade anything, so it looks like it's in sync with the current state of Ubuntu 22.04.

Looking through the logs you attached, it seems Vagrant uses **bsdtar** to extract files from the .box tar archive, and then triggers an error when it cannot parse the `metadata.json` file. Try extracting that file from the archive with

```
/opt/vagrant/embedded/bin/bsdtar -x -f eos.box metadata.json
```

... and check what you get in metadata.json.

**Comment by jotasantos** [comment]
I manually applied bsdtar/ eos.box stayed the same but metadata.json changed from:
{"provider":"libvirt","format":"qcow2","virtual_size":4}
to:
{
    "provider": "libvirt",
    "format": "qcow2",
    "virtual_size":
}
Which I think is equivalent expect for the missing '4'.  I ran 'vagrant box add box.json' with the new metadata.json as it was and then adding the "4". I got the same error. Attached complete run.
[run-20240414.txt](https://github.com/ipspace/netlab/files/14971894/run-20240414.txt)

**Comment by ipspace** [comment]
Great, we found the culprit. It's the **create_box.sh** script we download from vagrant-libvirt repository. It uses some weird awk magic to calculate the virtual_size parameter (whatever that means) and that magic seems to produce invalid result.

If you want to get a working box out of this morass, you'd have to unpack the *.box file, fix the metadata.json, and then repack the three unpacked files with tar back into *.box file (see create_sh.box for details).

I will try to reproduce what that script does in Python (so we can avoid the script), but it will take a few days. In the meantime, it would be great if you could unpack the .box files you generated with bsdtar and send me the output of qemu-img used by the create_box.sh script so I can figure out what broke that script.

```
$ mkdir /tmp/box
$ cp eos.box /tmp/box
$ cd /tmp/box
$ /opt/vagrant/embedded/bin/bsdtar -x -f eos.box
$ qemu-img info --output=json box.img
```

**Comment by jotasantos** [comment]
$ /opt/vagrant/embedded/bin/bsdtar -x -f eos.box
$ cat metadata.json
{
    "provider": "libvirt",
    "format": "qcow2",
    "virtual_size": 
}
jaime@jaime:/tmp/veos$ qemu-img info --output=json box.img
{
    "virtual-size": 4301258752,
    "filename": "box.img",
    "cluster-size": 65536,
    "format": "qcow2",
    "actual-size": 1173032960,
    "format-specific": {
        "type": "qcow2",
        "data": {
            "compat": "1.1",
            "compression-type": "zlib",
            "lazy-refcounts": false,
            "refcount-bits": 16,
            "corrupt": false,
            "extended-l2": false
        }
    },
    "dirty-flag": false
}

And you're correct, the awk parses the value in rounded Gig wrongly. But why your create_box.sh parses it right and mine doesn't? Maybe my  "virtual-size": 4301258752, is too big? What is yours?
$ qemu-img info --output=json box.img | awk '/^\s{0,4}"virtual-size/{s=int($2)/(1024^3); print (s == int(s)) ? s : int(s)+1 }'
$
jaime@jaime:/tmp/veos$ free -m
               total        used        free      shared  buff/cache   available
Mem:           60263         924       53595          29        5742       58667
Swap:           2047           0        2047

**Comment by ipspace** [comment]
Looks like the newer images are greater than 2^32, and AWK has 32-bit arithmetics. Will fix this and get rid of create_box.sh script for good. Give me a week or so.

**Comment by ipspace** [comment]
@jotasantos Removed the 'create_box.sh' script. I'm creating 'metadata.json' directly in 'netlab libvirt' and I was able to build the vEOS image with the latest SW (4.31.2F).

You could pull down the Git repo and run 'netlab' from there, or wait for the .post1 release (I will probably push it out tomorrow).
