### ISSUE TITLE
[BUG] Make sure nodes with 'vrf' module have 'vrfs' dictionary

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1109]
This is a spinoff from #1105. Based on commit text, it looks like we could get a situation where a node has **vrf** module enabled but no **vrfs** dictionary. That makes no sense and just increases the complexity of the configuration templates.

@ssasso: Could you provide a sample topology in which you experienced this bug? Thank you!

**Comment by ssasso** [comment]
I add the default to "vrfs" because of the "netlab initial -o" issue, not because the node has vrf module.
In fact, the node did not have vrf enabled.

**Comment by ipspace** [comment]
Thank you, closing this one.
