### ISSUE TITLE
[BUG] PMTUD does not work across Aruba CX

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1121]
It seems that Aruba CX does not generate ICMP fragmentation-needed unreachables required to make PMTUD work.

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/initial/01-interfaces.yml
* Validation results: https://netlab-cicd.pages.dev/arubacx/libvirt/initial/01-interfaces.yml-validate.log

This is a cosmetic issue, please feel free to close it immediately ;)

**Comment by ssasso** [comment]
This seems a limitation on the virtual image. Will add an item on the AOS-CX caveats.
