### ISSUE TITLE
[BUG] ArubaCX: incorrect IPv6 prefix advertised for OSPF loopbacks

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1123]
Similar to Cisco IOS and NXOS, it seems like ArubaCX assumes the IPv6 prefix length on a loopback interface is /128 regardless of what the actual configured prefix is. I had to use **ospf network-type point-to-point** on Cisco devices to force them to use the configured prefix

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/ospf/ospfv3/02-areas.yml
* Validation results: https://netlab-cicd.pages.dev/arubacx/libvirt/ospf/ospfv3/02-areas.yml-validate.log

**Comment by ssasso** [comment]
Unfortunately I was not able to find a similar workaround for AOS-CX :-(

**Comment by ipspace** [comment]
> Unfortunately I was not able to find a similar workaround for AOS-CX :-(

Because AOS-CX works like RFC 5340 says it should. See https://datatracker.ietf.org/doc/html/rfc5340#section-4.4.3.9

I'm going to fix the test and all the templates I 'fixed' the wrong way :((
