### ISSUE TITLE
[BUG] Multi-area OSPFv2/OSPFv3 configuration does not work on RouterOS7

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1127]
It looks like the OSPFv2/OSPFv3 configuration templates fail to configure any interfaces on RouterOS7 when the interfaces are in different areas.

### OSPFv2

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/ospf/ospfv2/02-areas.yml
* Validation results: https://netlab-cicd.pages.dev/routeros7/libvirt/ospf/ospfv2/02-areas.yml-validate.log

### OSPFv3

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/ospf/ospfv3/02-areas.yml
* Validation results: https://netlab-cicd.pages.dev/routeros7/libvirt/ospf/ospfv3/02-areas.yml-validate.log

This is the configuration printout from the above OSPFv2 topology:

```
[admin@dut] > /routing/ospf/export
# 2024-04-27 17:27:24 by RouterOS 7.14.3
# software id =
#
/routing ospf instance
add disabled=no name=default4 router-id=10.0.0.1
```

And this is the configuration printout from a single-area configuration:

```
[admin@dut] > /routing/ospf/export
# 2024-04-27 17:24:53 by RouterOS 7.14.3
# software id =
#
/routing ospf instance
add disabled=no name=default4 router-id=10.0.0.1
/routing ospf area
add disabled=no instance=default4 name=main_2_0.0.0.0
/routing ospf interface-template
add area=main_2_0.0.0.0 disabled=no interfaces=loopback passive
add area=main_2_0.0.0.0 disabled=no interfaces=ether2
add area=main_2_0.0.0.0 disabled=no interfaces=ether3 type=ptp
```

**Comment by ssasso** [comment]
Apparently, RouterOS 7 now requires that the Area-ID is in the form `x.x.x.x`... will fix that.
