### ISSUE TITLE
[BUG] IBGP local-as might not work on Aruba CX

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1146]
When testing **neighbor local-as** functionality that would result in an IBGP session on Aruba CX, the neighbor on the Cumulus Linux side is in the **idle** state. It might be easiest to give up and say "we don't do that" ;)

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/08-ibgp-localas.yml
* Validation results: https://tests.netlab.tools/arubacx/libvirt/bgp/08-ibgp-localas.yml-validate.log

**Comment by ssasso** [comment]
You are right, that's not supported on AOS CX.

Also, the "template" is aware of that to avoid failures: 

https://github.com/ipspace/netlab/blob/33e49c79f87a4966f3ed2f989b71019272ef9147/netsim/ansible/templates/bgp/arubacx.macro.j2#L12

Will try to report the "error" as a device quirk (in a similar way for what you did in #1152 )

**Comment by ssasso** [comment]
No wait the mistake is even before... ;)
I declared `local_as_ibgp: true` on the device yaml... :|
