### ISSUE TITLE
[BUG] RouterOS7 might need a reset of BGP sessions in bgp.session template

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1151]
All bgp.session validation tests are failing for RouterOS7. Either the configuration template is broken, or RouterOS7 does not resend BGP updates after a configuration change, in which case the fix from #1150 might be applicable.

* Validation results: https://tests.netlab.tools/_html/routeros7-libvirt-bgp.session

**Comment by ssasso** [comment]
not related to BGP reset, but a stupid-typo-kind-of-bug. Fixing it.
