### ISSUE TITLE
[BUG] VyOS does not apply bgp.session parameters to unnumbered EBGP sessions

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1159]
It looks like VyOS applies bgp.session parameters only to neighbors with IPv4/IPv6 addresses. The unnumbered session is established, but VyOS does not advertise the default route over it.

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp.session/24-default-unnumbered.yml
* Validation results: https://tests.netlab.tools/vyos/clab/bgp.session/24-default-unnumbered.yml-validate.log

**Comment by ssasso** [comment]
yap, I found the issue.

I will refactor the template for better handling of all the capabilities, and fix the issue.
