### ISSUE TITLE
[BUG] VRF BGP seems to be broken on RouterOS7

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1161]
All BGP-related VRF tests are failing with neighbor being in "Active" (which usually means "not configured on the other end"). I hope I made sure to have the latest commit on the test server, and I reran the tests just in case...

Validation results: https://tests.netlab.tools/_html/routeros7-libvirt-vrf

**Comment by ssasso** [comment]
I made the templates on the early days of ROS7, and config stuff may have changed in the meantime.
Will recheck all the cases.
