### ISSUE TITLE
[BUG] VyOS IS-IS does not use multi-topology for IPv6

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1184]
It looks like VyOS does not configure FRR to use IS-IS multi-topology for IPv6

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/isis/02-ipv6.yml
* Validation results: [URL](https://tests.netlab.tools/vyos/clab/isis/02-ipv6.yml-validate.log)

**Comment by jbemmel** [comment]
So now we have a problem with 2 devices (https://github.com/ipspace/netlab/pull/1171)

SR Linux will be adding multi-topology support back shortly, but regardless of that: I still think there is a use case for ipv6 designs that do not use/require multi-topology

You can even do dual-stack using a single topology, which has advantages in resource scaling.

Could we reconsider making multi-topology mandatory, and add a feature flag to disable it when desired?

**Comment by ipspace** [comment]
> So now we have a problem with 2 devices (#1171)

No. You have a problem with one device, and there's a configuration command missing in the IS-IS configuration template of another device. VyOS is using FRR, and we know FRR does multi-.topology.

In totally unrelated news, Arista EOS does interoperate with FRR due to FRR creating malformed LSPs, and it doesn't seem like anyone cares enough to merge the PR into frr:master, so whatever. That's why we have https://netlab.tools/caveats/ and caveats in the test reports.

> SR Linux will be adding multi-topology support back shortly

Nice to hear that. I will rerun the tests once the image is available in the public repository.

> but regardless of that: I still think there is a use case for ipv6 designs that do not use/require multi-topology

Absolutely. As we've learned in the past, there's always someone claiming a use case for another nerd knob, and another niche design ;)

> You can even do dual-stack using a single topology, which has advantages in resource scaling.

... and disadvantages in other aspects, as Peter Paluch told you in a recent LinkedIn discussion.

> Could we reconsider making multi-topology mandatory, and add a feature flag to disable it when desired?

Nobody asked for this in two years since IS-IS was added to _netlab_, but you (or anyone else) are more than welcome to add a custom configuration template (or plugin) to your lab topologies if you feel that's needed.

**Comment by ipspace** [comment]
Looks like VyOS IS-IS CLI does not have a multi-topology setting, but we could tweak the FRR config with

```
vtysh -c 'configure' -c 'router isis VyOS' -c 'topology ipv6-unicast'
```

So here are the options:

* Do nothing ;)
* Tweak the FRR config
* Document the caveat.

Which one do you prefer @ssasso?

**Comment by ssasso** [comment]
I would not manually tweak the FRR configuration, because this will make not aligned the vyos collected config.

I will try to open a bug/fr to the VyOS team and/or try to submit them a PR.

**Comment by ssasso** [comment]
https://vyos.dev/T6332

**Comment by ipspace** [comment]
Thank you. Will document it as a caveat.
