### ISSUE TITLE
Load miscellaneous Linux kernel modules

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1211]
Following the discussion in #1210:

* We should check for the presence of prerequisite Linux kernel modules in device quirks (FRR and Cumulus Linux)
* Device quirks should prepare the list of required kernel modules (for example, in **defaults.providers.clab.kmodules**) during the lab topology transformation process
* clab provider should try to load those kernel modules during lab startup phase and abort if they are not available -- that's much better than crashing in some obscure place in an Ansible playbook.

Likewise, we should check for the presence of the VRF module in device quirks, disable FRR management VRF, and generate a warning if the VRF module is not available (not sure whether the same applies to Cumulus Linux, have to check).

**Comment by ssasso** [comment]
Can you please do the check also for VyOS? ;)

Thanks

**Comment by ipspace** [comment]
> Can you please do the checks also for VyOS? ;)

Sure. Will probably add a generic function that can be called from the quirks modules.
