### ISSUE TITLE
[BUG] devcontainer tagged 1.9.0-dev1 (latest in this case) has netlab 1.8.4 in it

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#1259]
I guess that's due to the fact that the container is built with:

```
python3 -m pip install --break-system-packages networklab
```

and that installs the current version available on PyPI (and not a "_pre-release_") (ref: https://pypi.org/project/networklab/#history )

Maybe instead of tagging with *latest* a dev-release container it can be tagged as *dev*, and use `pip --pre` to force the pre-release pip? (Or sth like that)

EDIT: seems that `--pre` is not working on the devcontainer, but forcing a release is. `pip3 install .... networklab==version`

**Comment by ipspace** [comment]
Oh, it's a veritable bug all right ;) Even worse, when I was writing that stuff, I knew I would have to fix this eventually, but was like "gee, that's good enough for now".

I guess it's not good enough any more 🤦‍♂️

**Comment by ipspace** [comment]
I think I finally got it right ;) The latest container has the :dev tag and should include netlab release 1.9.0-dev1

Now let's hope I haven't broken the regular image build...
