### ISSUE TITLE
MPLS support Arista cEOS

### ISSUE THREAD

**Issue by ubaumann** [ipspace/netlab#1267]
Does the new image ceos:4.32.1F support MPLS now?

I was aware of issues with the MPLS data plane on cEOS and wanted to know if I could make the control plane work for L3VPN.
After reading this long discussion https://github.com/srl-labs/containerlab/discussions/807, I thought I should also try to make the data plane work. And, of course, I used the newest image.

I needed to do more tests, but it turned out that I could do a small "pe" - "p" - "pe" VPN setup without any big issues.
I need to do more tests, but so far it looks like the newest container works well for my use case.

My setup is in the directory "netlab" here: https://github.com/NetAutLabs/mpls_l3_vpn_service (I need to clean up some stuff, but for now, it works (on Unbuntu and GitHub Codespaces)

When I want to use the `mpls` module from netlab I get the following message:
```
[ERRORS]  Errors found in topology.yml
[TYPE]    quirks: Arista cEOS (edge1) does not support MPLS. Use vEOS VM with libvirt provider
[TYPE]    quirks: Arista cEOS (edge2) does not support MPLS. Use vEOS VM with libvirt provider
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

a) Is there a way to ignore the error so I can do more testing?
b) What use cases need to be tested with the new version to remove this error message? Are there any automated tests?

Screenshot running the lab in codespaces:
![image](https://github.com/user-attachments/assets/dca0c6d5-e7a5-4583-b96d-c5ffd3c6b6ba)

PS: Thanks for the great work

**Comment by ipspace** [comment]
> Does the new image ceos:4.32.1F support MPLS now?

No idea, will test it later today or tomorrow. That would be lovely.

> a) Is there a way to ignore the error so I can do more testing?

Remove the error message from https://github.com/ipspace/netlab/blob/dev/netsim/devices/eos.py#L25

> b) What use cases need to be tested with the new version to remove this error message? Are there any automated tests?

https://github.com/ipspace/netlab/tree/dev/tests/integration/mpls

Will run them after I'm done with the crazy rabbit trails of EVPN.

**Comment by ipspace** [comment]
Thanks a million for the poke @ubaumann -- so nice to see MPLS working in cEOS ;)
