### ISSUE TITLE
Ansible can't login with SHH at netlab up

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1284]
I started to play with netlab yesterday. I created an iosv box , using the documented process. All went well, but when I tried to netlab up the example link-augumentation topology, the process fails when ansible tries to login through SSH into the created VMs. The error is a KEX error, and is prolly because paramiko dropped support for shh-rsa. 

The boxes are up, and I can login manually with OpenSSH client once I enable the legacy algos in .ssh/config. 

I know nothing about ansible, even less about how netlab interacts with it, it appears it uses paramiko and I could not force it to use the libssh provider, Ive set the ansible environment variables regarding the ssh library to use, and they seem ignored. 

How can I convince netlab / ansible to allow ssh-rsa connections, please?

**Comment by ipspace** [comment]
Oh that... :( This is what I have in my `~/.ssh/config`:

```
Host 192.168.121.*
    KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
    KexAlgorithms +diffie-hellman-group1-sha1
    PubkeyAcceptedKeyTypes +ssh-rsa
    HostbasedAcceptedAlgorithms +ssh-rsa
    HostKeyAlgorithms +ssh-rsa
    StrictHostKeyChecking accept-new
    UserKnownHostsFile /dev/null
```

Supposedly this is the minimum you need: https://netlab.tools/caveats/#cisco-iosv (coming from someone else with the same issue)

Obviously, it could be that a new Ansible release yet again broke something. What version of Ubuntu and Ansible are you using? `lsb_release -a` and `ansible --version` would give you the answers.

**Comment by ipspace** [comment]
BTW, did you install Ansible with "netlab install ansible" or in some other way?

**Comment by DanPartelly** [comment]
I am not on ubuntu. I am on Nixos Nixos doesnt have a package for netlab, so I made one which I build locally.  No netlab install, as that wont.
Ansible is 2.16.5. My ./ssh/config is OK like yours, but it gets ignored.  

What ansible version is installed by netlab install ... ? in nixos is very easy to create an overlay over a package and use an older version. 

Netlab works perfectly so far.   Very nice program. Its just ansible and Cisco Iosv which  act up. Seems there is no fast way out of this. Ill just have to understand  Ansible a bit. 

And another question, please. Do you have templates for iosvl2 switching images ?

**Comment by ipspace** [comment]
> I am not on ubuntu. I am on Nixos

You should have started with that ;)

> Ansible is 2.16.5

I'm at 2.16.7, but that shouldn't matter so much. Anyway, it looks like you're missing the ansible-pylibssh Python package that Ansible tries to use instead of Paramiko. More details @ https://www.ansible.com/blog/new-libssh-connection-plugin-for-ansible-network/

> What ansible version is installed by netlab install ... ?

Take a look at https://github.com/ipspace/netlab/blob/dev/netsim/install/ansible.sh -- it installs the latest version of Ansible (that tends to work reasonably well these days), but it also installs a bunch of other stuff, most of it for some reason or another ;)

> And another question, please. Do you have templates for iosvl2 switching images ?

No. What exactly would you like to use it for?

**Comment by DanPartelly** [comment]
> You should have started with that ;)

Yes, i should have started with that. This appears to be a Nixos issue.  ansible-pylibssh is installed as a dependency by ansible, but for some reason, it is not picked up correctly by ansible. Im sorry I wasted your time. 

> No. What exactly would you like to use it for?
I want to learn netlab as i find it interesting. So I tough, recreate some old switching labs I have and I enjoyed, and see how far the viosl2 images has come in terms of quality.   

Can netlab build libvirt boxes from templates stored in user directories ? Like it apeears to load plugins from user search paths ?  Cause it would be very easy for users then to write pairs of initial config / vm templates for more ios devices

**Comment by ipspace** [comment]
> This appears to be a Nixos issue. ansible-pylibssh is installed as a dependency by ansible, but for some reason, it is not picked up correctly by ansible. Im sorry I wasted your time.

Absolutely not a problem. It could be that you're missing the underlying libssh library or something similar. Anyway, create a really small playbook in the lab directory and execute it with **ansible-playbook** to simplify the troubleshooting (I can create the playbook if needed).

Also, when you figure out the solution, please send it over so I'll add it to the caveats.

> I want to learn netlab as i find it interesting. So I tough, recreate some old switching labs I have and I enjoyed, and see how far the viosl2 images has come in terms of quality.

Is viosl2 anything more than a VLAN-capable switch? You could use **frr** to have a simple VLAN-aware Linux switch.

> Can netlab build libvirt boxes from templates stored in user directories? Like it apeears to load plugins from user search paths? Cause it would be very easy for users then to write pairs of initial config / vm templates for more ios devices

It can take Vagrantfile template from user directory, or the configuration templates, but not the box-building template. However, those are just a convenience mechanism, and if viosl2 is similar enough to IOS, you could just build an IOS box and then rename it (in box.json file)

The configurable search paths (and how they're are used) are described in the developer documentation:

https://netlab.tools/dev/config/deploy/

**Comment by DanPartelly** [comment]
> Absolutely not a problem. It could be that you're missing the underlying libssh library or something similar. Anyway, create a really small playbook in the lab directory and execute it with **ansible-playbook** to simplify the troubleshooting (I can create the playbook if needed). 
> Also, when you figure out the solution, please send it over so I'll add it to the caveats.

Ive got it working half an hour ago. This is exactly he method I use, made a simple playbook and started hunting down the issue. After confirming it uses libssh with -vvvv, I used bpftrace to snoop open syscalls and see if ./ssh/config is opened. It was. So I  emptied it, and started with an empty file. 

It turns out that any +  (used to append algos) in ssh client file renders the ssh client lib unable to negotiate a connection. This seems to point at a parsing problem inside libssh (version installed is  0.10.6), but I didnt really hunted it down in libssh code. I just want to play with netlab.   Anyways a config like below works and I was finally able to completely launch the sample labs. If you add a +, anywhere, it stops working. 

`Host 192.168.121.*
	KexAlgorithms diffie-hellman-group-exchange-sha1
        HostKeyAlgorithms ssh-rsa
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null`  

> Is viosl2 anything more than a VLAN-capable switch? 

Ive got a L2 image running in netlab in several minutes after I got the ssh issue down.   I didn't tried it's capabilities , but according to some people last switching  images from Cisco  can do a lot. spanning tree, etherchannel and whatever else. See below some labs from eve NG made with the 2019 image (there are newer ones out a 2020 L2 vios image and allegedly 2 very recent IOU (L2/L3 pair ) images in latest Cisco modelling Labs.) 
[https://www.eve-ng.net/index.php/lab-library/lab1/](url)

**Comment by ipspace** [comment]
> It turns out that any + (used to append algos) in ssh client file renders the ssh client lib unable to negotiate a connection. This seems to point at a parsing problem inside libssh (version installed is 0.10.6), but I didnt really hunted it down in libssh code.

Crazy. I vaguely remember experiencing something similar, but never chased it to conclusion. Also, Ansible seems to have solved that problem with ansible-pylibssh (at least on Ubuntu)

> I just want to play with netlab. Anyways a config like below works and I was finally able to completely launch the sample labs. If you add a +, anywhere, it stops working.

I'm almost afraid to add that to the caveats as it could break access to all the newer boxes. Will try to word it very carefully.

> > Is viosl2 anything more than a VLAN-capable switch?
> 
> Ive got a L2 image running in netlab in several minutes after I got the ssh issue down.

Awesome. So you just pretend it's an IOSv image and it works... but lacks a lot of configuration commands?

**Comment by DanPartelly** [comment]
> Crazy. I vaguely remember experiencing something similar, but never chased it to conclusion. Also, Ansible seems to have solved that problem with ansible-pylibssh (at least on Ubuntu)

ansible-pylibssh is in use on my system as well, since its basically the only thing which can load libssh in ansible. The crazy thing is, I brought up the cumulus example labs, and lo and behold, the ssh connection managed by paramiko, and despite ~/.ssh/config being crippled by the lack of append, netlab works. But of course I can not use OpenSsh client CLI with that config to log in in any of the cumulus VMs. 

So, ansible is weird. I kinda expect SW to not switch back-ends behind my back, and if it fails, fail as noisy as possible, with relevant errors. As in "I failed parsing" not "I failed KEX". Pipe dream.
> 
> I'm almost afraid to add that to the caveats as it could break access to all the newer boxes. Will try to word it very carefully.

Give me a few days, and ill look more into it. At first sight it seems that ",' is parsed OK , so you can at least concatenate more ciphers and make an exhaustive list, which would make for a very verbose config, but at least a working one for many situations. I cant promise I will get to the very bottom of it as I have no desire to debug this, but at least I can come with a config which works for newer devices as well. 

> Awesome. So you just pretend it's an IOSv image and it works... but lacks a lot of configuration commands?
Didn't really checked. It came up with 1 Gb interface. This mechanism I don't quite understand, since in GNS3 1 network interface in the VM creates 4 interfaces on the switch . If you can explain this a bit it would be great.  

Tomorrow or Monday Ill write an initial config for it, so at least we have management on it. then bother about the rest, and then in next week look at the image L2 capabilities. Maybe if it really supports etherchannel, STP, RSTP, MST, SPAN it would be worthy to make a proper integration in netlab

**Comment by ipspace** [comment]
> So, ansible is weird. I kinda expect SW to not switch back-ends behind my back, and if it fails, fail as noisy as possible, with relevant errors. As in "I failed parsing" not "I failed KEX". Pipe dream.

Ansible is so weird in so many ways that I stopped caring 🤷‍♂️ Unfortunately, it's still the easiest way to push configurations to dozens of platforms without spending too much time dealing with vendor quirks.

> Give me a few days, and ill look more into it. At first sight it seems that ",' is parsed OK , so you can at least concatenate more ciphers and make an exhaustive list, which would make for a very verbose config, but at least a working one for many situations.

That's exactly what I put in the caveats, so let's leave it at that. 

https://github.com/ipspace/netlab/blob/dev/docs/caveats.md?plain=1#L101

> Didn't really checked. It came up with 1 Gb interface. This mechanism I don't quite understand, since in GNS3 1 network interface in the VM creates 4 interfaces on the switch . If you can explain this a bit it would be great.

Don't want to know the details. libvirt is weird enough for me.

> Tomorrow or Monday Ill write an initial config for it, so at least we have management on it.

Do try adding this to `~/.netlab.yml` (user defaults file):

```
devices.iosvl2:
  parent: iosv
  libvirt.image: cisco/iosvl2
```

That should make a device that's almost exactly IOSv but has a different image name (so you can build a Vagrant box for it). Try using the same initial configuration as IOSv (maybe the management VRF won't work), then try various integration tests to see how much of _netlab_ functionality it supports. It should use the same configuration templates as IOSv.

**Comment by ipspace** [comment]
... you'd also need a Vagrantfile template `iosvl2-domain.j2` in the correct directory. It should probably be identical to

https://github.com/ipspace/netlab/blob/dev/netsim/templates/provider/libvirt/iosv-domain.j2

Also, if a relevant image would by some miracle drop into my lap, I could do the initial integration ;)

**Comment by DanPartelly** [comment]
> ... you'd also need a Vagrantfile template `iosvl2-domain.j2` in the correct directory. It should probably be identical to
> 
> https://github.com/ipspace/netlab/blob/dev/netsim/templates/provider/libvirt/iosv-domain.j2
> 
> Also, if a relevant image would by some miracle drop into my lap, I could do the initial integration ;)

Thanks for all the advice and your support. Im happy with my progress today with netlab.  Miracles happen by mail =)
