### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1290]
Might be worthy to clarify how an image is chosen when no version specialization is specified in the lab,and multiple images with different versions are available. What is the algo to choose a default image ? 

Ive been burned by this while treating L2 iosv images as "generic iosv".  Easy to fix with all the tools you make available in netlab,  (-vvv  shed light instantly ) but even so, a doc entry on of how the default image is chosen might be OK.

**Comment by ipspace** [comment]
Fair point, will add.

**Comment by ipspace** [comment]
Added a more explicit description in two places. Hope it's visible enough.
