### ISSUE TITLE
Add software releases used in integration tests to test reports

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1296]
Based on https://github.com/ipspace/netlab/discussions/1295#discussioncomment-10486601 by @hellt

**Comment by ipspace** [comment]
The only device for which this would be relevant is SR Linux (the functionality and configuration mechanism netlab uses for all other devices is stable and hasn't changed for years), so it doesn't really make sense to implement this.

**Comment by jbemmel** [comment]
> The only device for which this would be relevant is SR Linux (the functionality and configuration mechanism netlab uses for all other devices is stable and hasn't changed for years), so it doesn't really make sense to implement this.

Also relevant to [Cumulus NVUE](https://github.com/ipspace/netlab/issues/1954#issuecomment-2673691377)
