### ISSUE TITLE
Doc fix: cleanup after a reboot

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1322]
We should mention somewhere that it's best to shut down the labs before powering off the server, and described the cleanup procedure.

_Originally posted by @matthoug in https://github.com/ipspace/netlab/discussions/1321_

**Comment by jbemmel** [comment]
Could consider to set https://containerlab.dev/manual/nodes/#auto-remove on VMs

**Comment by ipspace** [comment]
> Could consider to set https://containerlab.dev/manual/nodes/#auto-remove on VMs

That just sets the '--rm' flag. It won't clean up Docker networks or other artifacts like clab_files or other directories containerlab creates. The only way to do a proper cleanup is to run 'netlab down --cleanup'

**Comment by jbemmel** [comment]
> > Could consider to set https://containerlab.dev/manual/nodes/#auto-remove on VMs
> 
> That just sets the '--rm' flag. It won't clean up Docker networks or other artifacts like clab_files or other directories containerlab creates. The only way to do a proper cleanup is to run 'netlab down --cleanup'

It also prevents setting the restart policy for Linux containers: https://github.com/srl-labs/containerlab/blob/main/runtime/docker/docker.go#L506

But you are right - it doesn't cleanup everything
