### ISSUE TITLE
Default SSH timeout

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1326]
Is there any specific reason why the initial configuration of the devices uses the default ssh timeout ?  

If not, could we modify it so it never timeouts? For example on iosv device we could have a  exec-timeout 0 under line vty 0 - 4, and later "fix" the setting on as many other devices as possible ?

Yesterday I spent ~4h working with netlab and other tools in parallel working on the bridge not passing traffic on multiaccess links problem and it became tiresome to have sessions timeout and  have to reconnect just to issue a ping.

**Comment by ipspace** [comment]
> Is there any specific reason why the initial configuration of the devices uses the default ssh timeout ?

No.

> If not, could we modify it so it never timeouts? For example on iosv device we could have a exec-timeout 0 under line vty 0 - 4, and later "fix" the setting on as many other devices as possible ?

That's how I set things up in the old days when I was still working on labs for hours. Please make the changes to the ios.j2 initial configuration template and submit a PR ;)

**Comment by ipspace** [comment]
Fixed by #1364
