### ISSUE TITLE
Dell OS10 templates always create virtual-network interfaces for VLANs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1333]
https://github.com/ipspace/netlab/blob/eb60af9f0691ff35ba3cd238717170cf21e2651f/netsim/ansible/templates/vlan/dellos10.j2#L8

See https://www.dell.com/support/manuals/en-in/dell-emc-smartfabric-os10/vxlan-evpn-ug-10-5-1-pub/virtual-network?guid=guid-dba77ee3-5a15-456b-83f4-8f36f4318386&lang=en-us: 
```virtual-network``` creates a VXLAN interface. That is not called for when creating plain VLANs, and is only supported starting 
release 10.4.2.0 or later

I haven't tested this, but I suspect it would be possible to create a more 'bare bones' template which would work also on older releases

**Comment by jbemmel** [comment]
> I deliberately decided to implement the templates that way, after years of experience on os10 physical devices (and virtual then).
> 
> A virtual network does not always create vxlan. It is a sort-of abstraction layer to simplify the integration.
> 
> Additionally, using virtual-network interface types is better supported on the virtual version apart from some caveats.

ok, fair enough - I don't have your experience, but I'm looking to use netlab to generate configs for some older OS10 devices that do not support that abstraction.

Furthermore, even with more current devices I've already hit some limitations - like not supporting OSPF on those virtual interfaces. I may need to create some variations - would we prefer a different device name (say dellos10-legacy) or a flag that chooses the variant?

**Comment by ipspace** [comment]
I understand that you need variations on the existing templates, but please implement them as local extensions within `~/.netlab/templates` directory. See https://netlab.tools/dev/config/deploy/ for more details.

I don't see too many people using Dell OS10, Dell seems not to care a bit about people not using GNS3, and testing Dell OS10 configurations is a nightmare. Also, I learned the hard way that things that are not thoroughly tested sometimes tend to have the annoying property of not working.
