### ISSUE TITLE
Check uses 'sshpass' without checking for its existence

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1334]
https://github.com/ipspace/netlab/blob/eb60af9f0691ff35ba3cd238717170cf21e2651f/netsim/ansible/tasks/readiness-check/dellos10.yml#L10

The password used is 'vagrant' even when using clab provider (as defined in group vars)

**Comment by ipspace** [comment]
Are you saying "I don't have sshpass installed" or "we're using the wrong password"?

**Comment by jbemmel** [comment]
First problem was that I did not run 'netlab install ubuntu' and hence sshpass wasn't installed; the check was failing silently because of that. Beyond that, I could already see the next problem once I did install sshpass, more like a 'note to self' when peeling the onion

**Comment by ipspace** [comment]
@ssasso It looks like we should:

* Rename dellos10.yml into dellos10-clab.yml and remove the "are we using clab" checks
* Replace the ssh call with "include_tasks: vm-clab-ssh-check.yml" in dellos10.yml
* Add the "do we have sshpass" check into vm-clab-ssh-check.yml

I can do the last bit in a day or two. Can you test the OS10-specific parts (I won't waste my time trying to build an OS10 container)?

@jbemmel: And what might he "next problem" be?

**Comment by ssasso** [comment]
> @ssasso It looks like we should:
> 
> * Rename dellos10.yml into dellos10-clab.yml and remove the "are we using clab" checks
> * Replace the ssh call with "include_tasks: vm-clab-ssh-check.yml" in dellos10.yml
> * Add the "do we have sshpass" check into vm-clab-ssh-check.yml
> 
> I can do the last bit in a day or two. Can you test the OS10-specific parts (I won't waste my time trying to build an OS10 container)?

Yes, I will try to have a new working container image, there are also some "new" caveats on that which I documented on vrnetlab page here: https://github.com/hellt/vrnetlab/tree/master/ftosv#caveats--working-vs-non-working-images

The last sentence needs to be converted in: "it seems, but sometimes it seems not" :(

**Comment by jbemmel** [comment]
> Yes, I will try to have a new working container image, there are also some "new" caveats on that which I documented on vrnetlab page here: https://github.com/hellt/vrnetlab/tree/master/ftosv#caveats--working-vs-non-working-images
> 
> The last sentence needs to be converted in: "it seems, but sometimes it seems not" :(

Yep, saw that. Have been trying to make the prompt scraping logic more robust, but it's finicky

**Comment by jbemmel** [comment]
> @jbemmel: And what might he "next problem" be?

Seeing the "vagrant" password suggested to me that things might not be designed/tested to work with Containerlab - even after I installed sshpass, the connection still didn't work

**Comment by ssasso** [comment]
> > @jbemmel: And what might he "next problem" be?
> 
> Seeing the "vagrant" password suggested to me that things might not be designed/tested to work with Containerlab - even after I installed sshpass, the connection still didn't work

I actively used dellos10 with containerlab multiple times in the past - even if sometime I had to restart the topology due to issues with vrnetlab initialization. I.e., all these tests: https://stefano.dscnet.org/a/multivendor_evpn_vxlan/ were performed with netlab+containerlab.

**Comment by jbemmel** [comment]
> I actively used dellos10 with containerlab multiple times in the past - even if sometime I had to restart the topology due to issues with vrnetlab initialization. I.e., all these tests: https://stefano.dscnet.org/a/multivendor_evpn_vxlan/ were performed with netlab+containerlab.

"NOTE: Since netlab creates an iBGP session between the two RR (the spines), I created a direct link between the two switches to avoid this session to go through leaf links. In real world scenarios, spines are not connected to each-other, and an iBGP session between them shall not exist."

In my real world, OS10 "spines" are connected through 4 VLT links :)

**Comment by ipspace** [comment]
> Seeing the "vagrant" password suggested to me that things might not be designed/tested to work with Containerlab - even after I installed sshpass, the connection still didn't work

That seems to be correct. Please add the required clab group vars (example in eos.yml) and submit a PR.

**Comment by ipspace** [comment]
> "NOTE: Since netlab creates an iBGP session between the two RR (the spines), I created a direct link between the two switches to avoid this session to go through leaf links. In real world scenarios, spines are not connected to each-other, and an iBGP session between them shall not exist."

That is easy to solve with a plugin ;)

**Comment by ssasso** [comment]
> > @jbemmel: And what might he "next problem" be?
> 
> Seeing the "vagrant" password suggested to me that things might not be designed/tested to work with Containerlab - even after I installed sshpass, the connection still didn't work

Btw, you are right regarding the password.... I never encountered the issues because I always used this in my topology 🤦‍♂️ 

```
defaults.devices.dellos10:
  clab:
    image: vrnetlab/vr-ftosv:10.5.6.0
  group_vars:
    ansible_user: admin
    ansible_ssh_pass: admin
```

apologies...

**Comment by ipspace** [comment]
To start with, let's note that this discussion has nothing to do with the issue you opened.

> So first you tell me we've been doing iBGP sessions since the early '90s and I'm <whatever> for wanting to remove them, but now it's ok to remove them as long as we use a plugin? Which one is it? ;)

We had this discussion in the past, resulting in https://blog.ipspace.net/2022/02/bgp-rr-myths/. The lesson I learned from that and similar discussions we had is that it makes no sense to discuss design preferences.

Adding nerd knobs to netlab to support those design preferences is a different story. You can write a simple plugin that implements whatever design tweaks you want to have, and that was all I wanted to say. However, don't expect that plugin to be made part of netlab package, but please feel free to add it to netlab-examples repo.
