### ISSUE TITLE
[DOC] Finalize IOL/IOLL2 documentation

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1376]
Just so we don't forget ;) The IOL/IOLL2 documentation needs:

* Caveats (for example, containerlab version)
* Link to caveats from platforms.md
* IOL/IOLL2 mentioned everywhere CSR and Cat8000v are mentioned

**Comment by DanPartelly** [comment]
Can you please be more specific on what you want to mention in docs where IOS/XE is previously mentioned ?
The particular image with version 17.12.01 is XE variant, so I guess we should coder this as well.

[Question moved here from the discussion in the original PR.]

**Comment by ipspace** [comment]
[Answer from the original PR ;)]

No worries, I'll fix that (I know where to look ;). So it's XE-based (like CSR and Cat8000v) and can support unnumbered IPv4? That's the major difference between IOSv and CSR IIRC.

**Comment by DanPartelly** [comment]
I didn't run a full lab with it but I checked now and at least the commands are accepted:

e1#show running-config | se interface Ethernet2/3
interface Ethernet2/3
 ip unnumbered Loopback0

e1#show ip int brief
.......................
Ethernet2/2            unassigned      YES unset  up                    up      
Ethernet2/3            10.0.0.1        YES unset  up                    up      
Loopback0              10.0.0.1        YES manual up                    up

**Comment by ipspace** [comment]
> I didn't run a full lab with it but I checked now and at least the commands are accepted:

Thank you, will fix the docs in the next few days.

**Comment by DanPartelly** [comment]
1. IP Unnumbered: supported
2. Layer 1 state: unsupported. Interface stops forwarding traffic, but state signaling is not working
3. No restconf / netconf
4. No EEM applets
5. Reserved VLANs on L2 image, like on most Cisco devices

**Comment by ipspace** [comment]
> 1. IP Unnumbered: supported

👍

> 2. Layer 1 state: unsupported. Interface stops forwarding traffic, but state signaling is not working

Do you mean "if I shut down the vEth interface, the device doesn't notice" or "if I shut down the interface on IOL, the state is still up"?

> 3. No restconf / netconf
> 4. No EEM applets
> 5. Reserved VLANs on L2 image, like on most Cisco L2 devices

🤷‍♂️

**Comment by ipspace** [comment]
Open questions:

* Segment routing support on IOL (no modifications to sr-mpls.md)
* MPLS support on IOL (changed "IOS XE" references to "CSR 1000v" for the moment as MPLS does not work on Cat8Kv)
* VXLAN support on IOL (right now, one CSR is mentioned)

You can use the integration tests to figure out what works (I just have to write the supporting documentation, should be able to do it this week).

Anyway, we can fix the unknown stuff later, or leave it as it is ;)
