### ISSUE TITLE
IOL devices support - introduce quirks

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1377]
On L2 images, like on most Cisco devices, there are reserved VLANs.
We should introduce quirk classes for it, and other potential issues, like netlab has for other image types.

I will doit sometimes this week.

**Comment by ipspace** [comment]
If the range is the same as for IOSvL2, just symlink `devices/iosvl2.py` into `ioll2.py` (and adapt the error message to mention both platforms). Otherwise, `iosvl2.py` might be a good starting point.
