### ISSUE TITLE
MPLS on Cat8Kv needs an advance license

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1386]
You just have to upgrade the boot license to 'advantage' or 'premier' for MPLS/SRv6 support:

```
license boot level network-premier addon dna-premier
```

_Originally posted by @kaelemc in https://github.com/ipspace/netlab/issues/1381#issuecomment-2418564907_

**Comment by kaelemc** [comment]
Just to caveat, this means the node has to be rebooted once this config is applied as the license is applied on *node boot*.

**Comment by ipspace** [comment]
> Just to caveat, this means the node has to be rebooted once this config is applied as the license is applied on _node boot_.

So we have to change the box building recipe. Thanks a million, saved me quite some time ;)
