### ISSUE TITLE
[BUG]  * Glob pattern inconsistency 

### ISSUE THREAD

**Issue by DanPartelly** [ipspace/netlab#1395]
1. Use 31-vlan-bridge-trunk.yml topology. 

2. Run netlab report --node s* addressing. It succeeds for both nodes.
3. netlab report --node h* addressing. It fails. It is expected to  succeed on 4 nodes.
4. netlab report --node s*,h* addressing . It succeeds on all 6 nodes 
using git dev.

**Comment by ipspace** [comment]
Bash FAD (Functions-As-Designed). For whatever reason, it expand a glob if the glob matches something, but not otherwise. **h\*** usually matches:

```
$ ls -d h*
hosts.yml  host_vars
```

Also:

```
$ echo h*
hosts.yml host_vars
$ echo s*,h*
s*,h*
```

You have to quote the glob, for example, `netlab report --node 'h*' addressing`
