### ISSUE TITLE
[BUG] Change container "on-restart" action

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1399]
Recent containerlab versions start Linux containers with on-failure restart policy. Docker understands that as "restart after a server crash", restarting FRRouting (or IOSv) containers with no usable connectivity (because containerlab uses handcrafted vEth pairs).

The only sane way to fix this is to change the on-failure restart policy. The next containerlab version will include a configurable option (see https://github.com/srl-labs/containerlab/pull/2238) but I don't want to force everyone to upgrade _containerlab_ together with _netlab_ (although we are testing containerlab version during virtualization provider probes, so we could enforce that).

Another option would be to execute **docker** commands to change the policy in the clab **post_start_lab** hook, making this fix containerlab-version independent.

Any thoughts @hellt @jbemmel @DanPartelly @ssasso?

**Comment by hellt** [comment]
We are per-stage exec in #2241, so the workaround with post_start_lab hook won't last long.

I would enforce an upgrade, given that it is easy to upgrade containerlab

**Comment by ipspace** [comment]
Waiting for a new containerlab release
