### ISSUE TITLE
Ability to specify eos device identification numbers in topology

### ISSUE THREAD

**Issue by aceplean** [ipspace/netlab#1405]
EOS has a device serial number and a system MAC address identifying the instance. Netlab creates random values at spin-up.
It would be convenient in certain cases being able to pre-set one or both of these values by entering them in topology under the node.

Example of the values:
```
gw2#sh ver
Arista cEOSLab
Hardware version:
Serial number: 49CCB95CF768B841CC791ACB9A3CB2FF
Hardware MAC address: 001c.7324.e592
System MAC address: 001c.7324.e592
```

**Comment by ipspace** [comment]
netlab does not do anything. EOS takes the system MAC address from somewhere, and if you could figure out where it gets it, we might be able to do something. I have zero idea what they do for the serial number.

However, keep in mind that netlab uses Vagrant or containerlab to start the workload, and has no influence (apart from what they allow us to configure) on how they set things up. We can tweak things, but only after the VMs/containers are started, which might be a bit late.

**Comment by sdargoeuves** [comment]
There are some values you can override with Arista. I have used [this workaround](https://github.com/ipspace/netlab/discussions/910#discussioncomment-8871926) to set the SN on vEOS after reboot of the netlab server. I'd like to think it works the same on cEOS, but I haven't tested.

Related to cEOS, I came across this page recently: [Populate Arista cEOS Serial Number with Containerlab](https://campusnetworkengineering.com/posts/containerlab_populate_serial/)

Side note, not related to clab, but libvirt: I am currently using a pretty ugly workaround with virsh, to reuse the uuid from a backup of a dumpxml, so I can restart the vm and have it using the previous SN, as it seems the SN of some of the virsh/vagrant boxes are linked on the uuid (and the mac address), or at least this is the case for F5!

**Comment by ipspace** [comment]
> Related to cEOS, I came across this page recently: [Populate Arista cEOS Serial Number with Containerlab](https://campusnetworkengineering.com/posts/containerlab_populate_serial/)

Thank you!

> Side note, not related to clab, but libvirt: I am currently using a pretty ugly workaround with virsh, to reuse the uuid from a backup of a dumpxml, so I can restart the vm and have it using the previous SN

vagrant-libvirt plugin can specify the uuid, and the management MAC addresses are fixed any (or DHCP wouldn't work correctly), so we could add **libvirt.uuid** node option. Will you open an issue or should I? 😎

**Comment by sdargoeuves** [comment]
> vagrant-libvirt plugin can specify the uuid, and the management MAC addresses are fixed any (or DHCP wouldn't work correctly), so we could add libvirt.uuid node option. Will you open an issue or should I? 😎

I'm doing that now!

**Comment by aceplean** [comment]
Thanks @sdargoeuves, #910 is a can of worms but the method described for vEOS combined with [Populate Arista cEOS Serial Number with Containerlab](https://campusnetworkengineering.com/posts/containerlab_populate_serial/)) reference you provided I was able to set both the serial number and MAC from the topology file. Obviously this is specific to EOS but still uber useful.
Thanks to y'all contributors to these wonderful tools! You rock!

Here's my topology where I'm bind-mounting the serial number and MAC file (second bind)
```
provider: clab

defaults.devices.eos.clab.image: ceos:4.31.2F

nodes:
  temgm2:
    device: eos
    clab:
      binds:
        mymapping_json: '/mnt/flash/EosIntfMapping.json'
        my_ceos-config: '/mnt/flash/ceos-config'

links:
- temgm2:
```
Here's the content of my_ceos-config:
```
SERIALNUMBER=ABC12345678
SYSTEMMACADDR=1122.3344.5566
```
And here's the running container result:
```
temgm2>sh ver
Arista cEOSLab
Hardware version:
Serial number: ABC12345678
Hardware MAC address: 1122.3344.5566
System MAC address: 1122.3344.5566

Software image version: 4.31.2F-35442176.4312F (engineering build)
Architecture: x86_64
```

**Comment by ipspace** [comment]
> Thanks to y'all contributors to these wonderful tools! You rock!

Thanks a million. Made my day ;)

**Comment by sdargoeuves** [comment]
Amazing!! I've tested on cEOS, just using the `eos.serialnumber` works like a charm
Thank you so much!!
