### ISSUE TITLE
[BUG] Do not show generic devices or their (lack of) images

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1427]
Generic devices (junos, ios) probably should not be shown in **netlab show devices** or **netlab show images** printouts as they cannot be used on their own (the have no images associated with them)

Any thoughts @ssasso @DanPartelly @sdargoeuves

**Comment by ssasso** [comment]
Agree.
At the same time an error should be triggered if a user tries to use that.

Maybe a

`template: true`

On the device yaml can be a starting point?

**Comment by ipspace** [comment]
> Agree. At the same time an error should be triggered if a user tries to use that.

Yes, we can do that, together with a hint saying "use netlab show devices to display available devices"

> Maybe a `template: true` on the device yaml can be a starting point?

👍

**Comment by DanPartelly** [comment]
I think its a great idea as well.
