### ISSUE TITLE
Check for unicast MACs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1428]
https://github.com/ipspace/netlab/blob/1b3218cae21b1132321adae850db11dc1871baca/netsim/data/types.py#L761

In many (all?) cases I believe the MAC should be a unicast MAC address - we could validate that

**Comment by ipspace** [comment]
> In many (all?) cases I believe the MAC should be a unicast MAC address - we could validate that

Agree, makes perfect sense. Will you implement that?

For future reference: if we ever need to recognize broadcast addresses, we can add an extra parameter to the validation function (similar to min_value / max_value on ints)
