### ISSUE TITLE
Double check hardcoded mgmt prefix

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1476]
https://github.com/ipspace/netlab/blob/1e1e376577bc7375370ee85c24a71f7c98426203/netsim/ansible/tasks/readiness-check/iosxr-libvirt.yml#L21

I don't use IOS XR, but shouldn't this be something along the lines of ```pools.mgmt.ipv4|ipaddr('netmask')```?

I'm guessing this corresponds to hardcoded addressing in netsim/templates/provider/libvirt/vagrant-libvirt.xml?

**Comment by ipspace** [comment]
1. `mgmt.ipv4` is an IPv4 address, not a prefix.
2. IIRC IOS XR used some DHCP client ID that resulted in unexpected management IP address.

**Comment by jbemmel** [comment]
Edited to clarify that I was talking about the "255.255.255.0" part - but ok with closing this, just double checking

**Comment by ipspace** [comment]
> Edited to clarify that I was talking about the "255.255.255.0" part - but ok with closing this, just double checking

Yeah, IOS XR is (like IOS) an old-school operating system ;)
