### ISSUE TITLE
[BUG] Make 'default', 'system' and 'global' VRF names invalid

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1509]
Some devices use _default_ (or _system_ or _global_) VRF as the global routing table. We should make these names invalid to avoid confusions.

**Comment by ipspace** [comment]
Any thoughts @jbemmel @ssasso @DanPartelly? Have I missed another keyword?

**Comment by ssasso** [comment]
there's a plethora of other names the different vendors uses as name for the management vrf :(

**Comment by jbemmel** [comment]
“base” for SR OS

**Comment by ipspace** [comment]
> there's a plethora of other names the different vendors uses as name for the management vrf :(

OK, we can exclude the obvious ones that are present when the device boots. Looking at the initial config templates, it seems like "junos_mgmt" is really a built-in name. True?

**Comment by ssasso** [comment]
> OK, we can exclude the obvious ones that are present when the device boots. Looking at the initial config templates, it seems like "junos_mgmt" is really a built-in name. True?

Correct.

But my memory failed and it is `mgmt_junos` :)

Ref: https://www.juniper.net/documentation/us/en/software/junos/junos-getting-started/topics/topic-map/management-interface-in-non-default-instance.html



```
The name of the dedicated management VRF instance is reserved and hardcoded as mgmt_junos; you cannot configure any other routing instance by the name mgmt_junos.
```

**Comment by DanPartelly** [comment]
Cummuls: default, unspec, main, or local. [1]
Also, Not sure but some Ciscos may not allow "all".

[[1]](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-43/Layer-3/VRFs/Virtual-Routing-and-Forwarding-VRF/)
