### ISSUE TITLE
AF-level control of BGP sessions

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#152]
Original comment made in #148 by @jbemmel and related responses

---------------

Although one could configure a different router_id for BGP and OSPF, I think it makes the most sense if it is the same.
I could add the 'loopback.ipv4|default(...)' logic to the templates, but I would prefer to have the 'initial' module do the honors
(or perhaps the 'augment' logic where loopbacks get calculated)

In my ipv6-only topology only the ipv6 BGP session comes up. If you say it's the sanest way to try both by default that's fine, but I'd still like a flag to say "don't configure ipv4 peers for bgp"

Perhaps
```
bgp:
 peering:
  ipv4: False
```
(may not be needed if we can have loopback without ipv4 address and still get a router_id)

----

> Ah, so you configured IPv4 loopbacks in an IPv6-only network (to get router IDs) and all of a sudden you have a bunch of IBGP IPv4 sessions. Yeah, that sucks ;)
> 
> I like the idea of controlling which sessions one wants to have (and we could extend it to EVPN or L3VPN sometime), but I think we need to have IBGP and EBGP parts, for example:
> 
> ```
> bgp:
>  peering:
>   ibgp:
>    ipv4: False
> ```

----

> I think the BGP session (ipv4 and/or ipv6) and the address families to enable are 2 different things
> 
> The current logic is like this:
> 
> ```
>     # Calculate BGP address families
>     for af in ['ipv4','ipv6']:
>       for n in node.bgp.neighbors:
>         if af in n:
>           node.bgp[af] = True
>           break
> ```
> 
> in other words, if a node has an ip address for the given family, enable that family.
> 
> Shall we add something like this?
> 
> ```
> bgp:
>   address_families: 
>    ibgp: [ ipv4, ipv6 ]
>    ebgp: [ ipv4, ipv6 ]
> ```
> 
> (to be extended with evpn, etc once we get to it )

**Comment by jbemmel** [comment]
Tentative PR here: https://github.com/jbemmel/netsim-tools/blob/srv6-support/netsim/topology-defaults.yml#L37

**Comment by ipspace** [comment]
We solved the 'router ID is missing' case. The only scenarios where I could see this being relevant are EVPN in IBGP-over-EBGP design (disable IPv4 on IBGP sessions) and 6PE (disable IPv6 on 6PE-enabled sessions). There might also be EVPN-with-SRv6 case (disable IPv4).

We can solve all these edge cases within the appropriate configuration modules or device configuration templates.
