### ISSUE TITLE
Libvirt code assumes a /24 mgmt subnet

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1524]
https://github.com/ipspace/netlab/blob/b07a71b5b069ae116cd1df77dae012a4bf876f34/netsim/providers/libvirt.py#L65

My topology has:
```
addressing:
 mgmt: 
   ipv4: 100.0.0.0/8
```

resulting in a crash as the 256 count no longer fits in 8 bits

One solution:
``` while d_start < min(d_net.size,256) - 2:```

(and perhaps a warning)

**Comment by ipspace** [comment]
Do you really have to try out every weird idea out there? Having a public /8 assigned to ARIN as the management subnet 🤦‍♂️

Yeah, you can limit the DHCP pool size.
