### ISSUE TITLE
[BUG] unmanaged device causing exception: box.exceptions.BoxTypeError: unhashable type: "Box"

### ISSUE THREAD

**Issue by sdargoeuves** [ipspace/netlab#1551]
### Describe the bug

Starting to think how I am going to connect the Cloud to netlab, I started to play with unmanaged devices. But using the example in the [documentation](https://netlab.tools/example/external/#unmanaged-devices), it fails [here](https://github.com/ipspace/netlab/blob/dev/netsim/providers/__init__.py#L333)

### To Reproduce

You can use the example in the doc:

```yaml
defaults.device: eos
module: [ bgp ]
nodes:
  vm:
    bgp.as: 65000
  sw:
    unmanaged: True
    bgp.as: 65001
links:
- vm:
    ipv4: 10.42.0.2/24
  sw:
    ipv4: 10.42.0.1/24
  libvirt.public: True
```

### Output

```shell
  ~/code/netsim-main-lab on   revival_q3_2024 !15 ❯ netlab create                                                                                             netsim-main-lab with sa@sa-netlab01a
Traceback (most recent call last):
  File "/home/sa/code/netsim-main-lab/venv/bin/netlab", line 14, in <module>
    netsim.cli.lab_commands(__file__)
  File "/home/sa/code/netsim-main-lab/venv/lib/python3.11/site-packages/netsim/cli/__init__.py", line 351, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sa/code/netsim-main-lab/venv/lib/python3.11/site-packages/netsim/cli/create.py", line 93, in run
    output_module.write(topology)
  File "/home/sa/code/netsim-main-lab/venv/lib/python3.11/site-packages/netsim/outputs/provider.py", line 35, in write
    providers.mark_providers(topology)
  File "/home/sa/code/netsim-main-lab/venv/lib/python3.11/site-packages/netsim/providers/__init__.py", line 333, in mark_providers
    l.provider[node.provider] = True
    ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "box/box.py", line 667, in box.box.Box.__setitem__
  File "box/box.py", line 386, in box.box.Box.__hash__
box.exceptions.BoxTypeError: unhashable type: "Box"

```

### Version

* netlab version: `1.9.2` and the current `main`

### Additional context

I've done this as a workaround, it allows the `netlab create` to complete:

```python
  for l in topology.links:                          # Set 'providers' attribute on all links
    for intf in l.interfaces:
      node = topology.nodes[intf.node]
      if node == {}:
        continue
      l.provider[node.provider] = True
```

**Comment by sdargoeuves** [comment]
The other things bothering me are:

* the first one is no longer an issue, as I've found the place in the docs regarding Connection to the Outside world, I didn't see this part. So using this, it works much better (I didn't add the uplink, I only had the public: True)

```yaml
links:
  - d1xfw01:
      ipv4: 101.0.0.1/30
    sw1:
      ipv4: 101.0.0.2/30
    libvirt:
      public: true
      uplink: enp195s0
    ospf: false
```

* if you do not have a default device type, netlab doesn't like it. Even using unknown doesn't work, as it expects a Vagrant image for this.

```shell
  ~/code/quick-netlab-lab/minitest ❯ devlab create                                                                                              netsim-main-lab with sa@sa-netlab01a
[ERRORS]  Errors found in topology.yml
[MISSING] nodes: No device type specified for node sw1 and there is no default device type
[MISSING] nodes: No device type specified for node sw2 and there is no default device type
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```

I could just configure a default, and that's no longer an issue!

* and the last one, I finally understood what's happening, I'll create a new ticket...

**Comment by ipspace** [comment]
Thanks a million for uncovering this one. Looks like I'll have to set up a similar topology and figure out what breaks under various scenarios.

**Comment by ipspace** [comment]
> The first one is no longer an issue, as I've found the place in the docs regarding Connection to the Outside world, I didn't see this part. So using this, it works much better (I didn't add the uplink, I only had the public: True)

Still, we might be able to generate an error (or a warning).

> if you do not have a default device type, netlab doesn't like it. Even using unknown doesn't work, as it expects a Vagrant image for this.

**none** should work, but then I agree that an **unmanaged** node does not need a device type. Maybe we should set the device type to **none** if it is not specified?

**Comment by sdargoeuves** [comment]
I was not aware and/or didn't think about using `none` option. It works fine with the option `none` for device type (although it took me a few attempts to realise I still had the batch setup to test the other issue 😆 )

> Maybe we should set the device type to none if it is not specified?

It could be good, unless we want to keep the current behaviour to force users to specify something and they will get an error if they don't. In which case, we could just add a note in the documentation to explain the `none` option for device type, probably close to the Unknown devices...

**Comment by ipspace** [comment]
Fixed all "related challenges" raised in this issue.

**Comment by sdargoeuves** [comment]
excellent, thank you so much!!
