### ISSUE TITLE
[BUG] Cumulus VX 4.x uses an ancient version of Python

### ISSUE THREAD

**Issue by adamcirillo** [ipspace/netlab#1590]
### Describe the bug

running netlab test libvirt gives the following error about python version but 3.12 is installed

TASK [Deploy initial configuration] *****************************************************************************************************************************************************************************************************
included: /usr/local/lib/python3.12/dist-packages/netsim/ansible/tasks/deploy-config/cumulus.yml for s1, s2, s3

TASK [copy cumulus config to /tmp/config.sh] ********************************************************************************************************************************************************************************************
fatal: [s3]: FAILED! => 
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'
fatal: [s1]: FAILED! => 
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'
fatal: [s2]: FAILED! => 
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'

PLAY RECAP ******************************************************************************************************************************************************************************************************************************
s1                         : ok=7    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
s2                         : ok=7    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
s3                         : ok=7    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

Error executing ansible-playbook /usr/local/lib/python3.12/dist-packages/netsim/ansible/initial-config.ansible:
  Command '['ansible-playbook', '/usr/local/lib/python3.12/dist-packages/netsim/ansible/initial-config.ansible']' returned non-zero exit status 2.
[FATAL]   Executing Ansible playbook /usr/local/lib/python3.12/dist-packages/netsim/ansible/initial-config.ansible failed
Error executing netlab initial --no-message:
  Command '['netlab', 'initial', '--no-message']' returned non-zero exit status 1.
[FATAL]   netlab up: netlab initial failed, aborting...
Error executing netlab up:
  Command '['netlab', 'up']' returned non-zero exit status 1.
[FATAL]   test: netlab up failed, aborting

==============================================================================
The test has failed. We will try to clean up the test directory and remove it,
but there's no guarantee that the cleanup process will succeed, in which case
please remove the test directory manually.

You might want to copy the error messages generated during the test before
proceeding. The cleanup process will start once you press RETURN.
==============================================================================

### To Reproduce

run netlab test libvirt

If you're experiencing any other unexpected behavior, please add the steps needed to reproduce it. 

### Expected behavior

Test Passes

### Lab topology

```
N/A
```

### Output

```
Please add the output you get when running `netlab create` on the minimum lab topology provided
```

### Version

1.9.2

### Additional context

Ubuntu 24.0.1 running as vm on hyper-v windows server 2022

**Comment by ipspace** [comment]
Ouch. It looks like we hit the shelf life of Cumulus VX 4.x VM. Cumulus VM comes with Python 3.7.

You should be able to use netlab with libvirt provider. The VMs started, so that part works, and Ansible tried to do stuff (but failed due to Python version differences). However, to help me figure out what's going on, please post the results of `pip3 list|grep ans` -- this is what I get on my server:

```
$ pip3 list|grep ans
ansible                  10.6.0
ansible-core             2.17.6
ansible-pylibssh         1.1.0
```

**Comment by adamcirillo** [comment]
here you go

ansible               11.0.0
ansible-core          2.18.0
ansible-pylibssh      1.2.2
bracket-expansion     1.0.0
s3transfer            0.10.1

**Comment by adamcirillo** [comment]
also there is this GitHub issue I found explaining the version bump https://github.com/ansible/ansible/issues/72668

**Comment by jbemmel** [comment]
```netlab test libvirt``` works on my system for the ```dev``` branch, it pulls Cumulus VX 4.4.5 which may have an old Python version but that doesn't explain why the test fails

**Comment by adamcirillo** [comment]
mine is grabbing 4.4.5 as well but i think because it installed ansible 11 and that needs python >= 3.8 is why its failing

**Comment by ipspace** [comment]
Ansible supports three Python releases between controller and controlled node (https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#support-life).

I'm on Ubuntu 22.04 which uses Python 3.10. Python 3.7 on CL 4.4.5 is thus OK.

You're on Ubuntu 24.x which uses Python 3.12, making the minimum Python release on the managed node 3.8, thus failing with CL 4.4.5.

I think we already have Ansible configuration task lists that do not rely on Python, so it should be relatively easy to use them for CL 4.4.
