### ISSUE TITLE
[BUG] IBGP not working on CL NVUE

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1594]
IBGP sessions never worked on CL NVUE because we could not set the source IP address of an IBGP session with early versions of NVUE data model (https://blog.ipspace.net/2022/10/cumulus-linux-nvue/). Now they want the AS number to be set to "internal", so even the config fails.

* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/03-ibgp-rr.yml
* Validation results: https://tests.netlab.tools/cumulus_nvue/libvirt/bgp/03-ibgp-rr.yml-initial.log

@jbemmel: I can try to fix this if you don't have time.

**Comment by jbemmel** [comment]
I'll fix it
