### ISSUE TITLE
Find a better VM to run FRRouting

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1595]
FRRouting currently uses Ubuntu 20.04 as later versions of Ubuntu tend to be multi-interface-challenged. Ubuntu 20.04 comes with Python 3.8 which barely works with Ansible 11.0 (see #1590 for details).

We need to find a long-term solution for FRR virtual machines (Debian?)

**Comment by jbemmel** [comment]
Cumulus uses Debian, that seems to work
