### ISSUE TITLE
[BUG] CL NVUE: BGP community propagation is not configured correctly

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#1606]
* Test topology: https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp/05-community.yml
* Validation results: https://tests.netlab.tools/cumulus_nvue/libvirt/bgp/05-community.yml-validate.log

I don't think this ever worked, and I'm OK to declare this a caveat and move on. What do you think @jbemmel?

**Comment by jbemmel** [comment]
I think it's missing the equivalent of https://github.com/ipspace/netlab/blob/ce0e8da8e6acde290e11fd6c7802921b54fab344/netsim/ansible/templates/bgp/frr.j2#L76

Shouldn't be too hard to add - I'll take a look
