### ISSUE TITLE
NSO Docker suppot

### ISSUE THREAD

**Issue by adamcirillo** [ipspace/netlab#1615]
Would it be possible to add the Cisco NSO docker image to a topology and have it run on the management network to connect to the routers? Could probably add it to the external tools section to add it to a topology?

**Comment by ipspace** [comment]
> Would it be possible to add the Cisco NSO docker image to a topology and have it run on the management network to connect to the routers?

Sure. Just add another node with **device: linux**, **provider: clab** and **image: whatever**. See also https://netlab.tools/example/linux/#tutorial-linux

If you want to reach other devices from the management network, add the NSO node to the **unprovisioned** group (https://netlab.tools/groups/#group-special-names), otherwise the initial configuration script puts the management interface into a VRF.

> Could probably add it to the external tools section to add it to a topology?

Of course. That would also allow you to build an initial configuration file from the transformed lab topology data (see SuzieQ for an example)

**Comment by adamcirillo** [comment]
I've come up with this for the yml but not sure how to add it to the topology.yml config to test it and where do i put the file?

```
#
# Cisco NSO tool
#
runtime: docker     # Default: start in a Docker container
docker:
  up:
    docker run -itd --name {name}-cisco-nso 
    {sys.docker_net}
    -v {name}-NSO-vol:/nso
    -v {name}-NSO-log-vol:/log
    -p { 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }:8080
    -e ADMIN_USERNAME-admin
    -e ADMIN_PASSWORD=admin
    -e EXTRA_ARGS='--with-package-reload --ignore-initial-validation'
    cisco-nso-prod 
  message:
    Open http://{sys.ipaddr}:{ 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }
    Use 'netlab connect nso' to start nso CLI
  connect:
    docker exec -it '{name}_cisco-nso' ncs_cli -u admin
  down:
    docker kill '{name}-cisco-nso'
  cleanup:
    docker volume rm '{name}-NSO-vol'
    docker volume rm '{name}-NSO-log-vol'
  config:
    - dest: nso-default.json
   ```

**Comment by ipspace** [comment]
> I've come up with this for the yml

Looks reasonable. The "config" element will need a "template" key to specify what template to use to create the config file. According to how I read the code ;) you'd have to put the template in the "tools/nso" subdirectory of the topology directory.

> but not sure how to add it to the topology.yml config to test it and where do i put the file?

Add the whole thing under **defaults.tools.nso** key, the enable the tool with **tools.nso:** (empty value, but it should add the tool to the lab topology).

**Comment by adamcirillo** [comment]
getting some errors starting up the lab i'm figuring i got a syntax error somewhere.
```
[ERRORS]  Errors found in nsotop.yml
[VALUE]   topology: Invalid runtime docker for tool nso
... valid runtimes are up,cleanup
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```
```defaults:
    device: iosxr
    provider: clab
    defaults.providers.clab.bridge_type: ovs-bridge
    devices.iosxr.clab.image: ios-xr/xrd-control-plane
    devices.ioll2.clab.image: vrnetlab/cisco_iol:L2-17.15.01
    devices.iol.clab.image: vrnetlab/cisco_iol:17.15.01
defaults.tools.nso:
  runtime: docker
  docker:
  up:
    docker run -itd --name {name}-cisco-nso 
    {sys.docker_net}
    -v {name}-NSO-vol:/nso
    -v {name}-NSO-log-vol:/log
    -p { 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }:8080
    -e ADMIN_USERNAME-admin
    -e ADMIN_PASSWORD=admin
    -e EXTRA_ARGS='--with-package-reload --ignore-initial-validation'
    cisco-nso-prod 
  message:
    Open http://{sys.ipaddr}:{ 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }
    Use 'netlab connect nso' to start nso CLI
  connect:
    docker exec -it '{name}_cisco-nso' ncs_cli -u admin
  down:
    docker kill '{name}-cisco-nso'
  cleanup:
    docker volume rm '{name}-NSO-vol'
    docker volume rm '{name}-NSO-log-vol'

nodes:
    R1:
        device: iosxr
        graphite.icon: router
        name: R1
        id: 1
        loopback:
            ipv4: 1.1.1.1/32   
    R2:
        device: iosxr
        graphite.icon: router
        name: R2
        id: 2
        loopback:
            ipv4: 2.2.2.2/32   
links:
   - R1-R2
tools:
  graphite:
  edgeshark:
  nso:
```

**Comment by ipspace** [comment]
All the docker-related settings (up, message, connect, down, cleanup) must be indented to be within the "docker" key.

**Comment by adamcirillo** [comment]
in the up: section can I run multiple docker commands as some configs in the container need to be edited to enable the webui in the download from cisco in this case using docker exec to do it

```
docker:
    up:
      docker run --rm -itd --name {name}-cisco-nso 
      {sys.docker_net}
      -v {name}-NSO-vol:/nso
      -v {name}-NSO-log-vol:/log
      -p { 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }:8080
      -e ADMIN_USERNAME-admin
      -e ADMIN_PASSWORD=admin
      -e EXTRA_ARGS='--with-package-reload --ignore-initial-validation'
      cisco-nso-prod 
      docker exec -it nso-cisco-nso sed -i.original -e "/<webui>/,/<\/webui>/ { /<transport>/,/<\/transport>/ { /<tcp>/,/<\/tcp>/ { /<enabled>/ s/false/true/ } } }" /etc/ncs/ncs.conf
      docker exec -it nso-cisco-nso sed -i.backup -e "/<local-authentication>/{n;s|<enabled>false</enabled>|<enabled>true</enabled>|}" /etc/ncs/ncs.conf
      docker exec -it nso-cisco-nso ncs --reload
```

**Comment by ipspace** [comment]
The tools are started in https://github.com/ipspace/netlab/blob/dev/netsim/cli/up.py#L266 which uses https://github.com/ipspace/netlab/blob/dev/netsim/cli/external_commands.py#L248

That function takes a list of commands (and https://github.com/ipspace/netlab/blob/dev/netsim/cli/external_commands.py#L217 does the string-to-list conversion if necessary), so it looks like the only thing you have to do is to change the "up" parameter from a single string into a list of strings (open command per list entry).

Don't remember ever testing it though (although I should have, considering I wrote that code 🤦‍♂️)

**Comment by adamcirillo** [comment]
i don't know much about python as i'm not really a programmer as i have dabbled a little bit in it from time to time but this is the error i'm getting. I tried running the commands with a ; like you can in bash but that came up with the same error.

```
Traceback (most recent call last):
  File "/usr/local/bin/netlab", line 14, in <module>
    netsim.cli.lab_commands(__file__)
  File "/usr/local/lib/python3.12/dist-packages/netsim/cli/__init__.py", line 351, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/netsim/cli/up.py", line 371, in run
    run_up(cli_args)
  File "/usr/local/lib/python3.12/dist-packages/netsim/cli/up.py", line 349, in run_up
    start_external_tools(args,topology)
  File "/usr/local/lib/python3.12/dist-packages/netsim/cli/up.py", line 281, in start_external_tools
    external_commands.execute_tool_commands(cmds,topology)
  File "/usr/local/lib/python3.12/dist-packages/netsim/cli/external_commands.py", line 255, in execute_tool_commands
    cmd = strings.eval_format(cmd,topology)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/netsim/utils/strings.py", line 116, in eval_format
    return str(eval(ex,dict(data)))      # An awful hack to use f-string specified in a string variable
               ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    f'docker run --rm -itd --name {name}-cisco-nso {sys.docker_net} -v {name}-NSO-vol:/nso -v {name}-NSO-log-vol:/log -p { 8888 + defaults.multilab.id if defaults.multilab.id else 8888 }:8080 -e ADMIN_USERNAME-admin -e ADMIN_PASSWORD=admin -e EXTRA_ARGS=\'--with-package-reload --ignore-initial-validation\' cisco-nso-prod docker exec -it {name}-cisco-nso sed -i.original -e "/<webui>/,/<\/webui>/ { /<transport>/,/<\/transport>/ { /<tcp>/,/<\/tcp>/ { /<enabled>/ s/false/true/ } } }" /etc/ncs/ncs.conf docker exec -it {name}-cisco-nso sed -i.backup -e "/<local-authentication>/{n;s|<enabled>false</enabled>|<enabled>true</enabled>|}" /etc/ncs/ncs.conf docker exec -it {name}-cisco-nso ncs --reload'
                                                                                                                                                                                                                                                                                                                                                                                                                ^
SyntaxError: f-string: expecting a valid expression after '{'
```

**Comment by ipspace** [comment]
> This is the error i'm getting.

The '{' characters in the **sed** command are interfering with the Python way of string formatting which also uses '{'

> I tried running the commands with a ; like you can in bash but that came up with the same error.

No idea whether that would work. The string is passed to **bash** though, so it might.

Anyway, you have to "quote" the extra '{' and '}' characters. The way to do that in f-strings is to replace what you want to be '{' with '{{' and likewise replace '}' with '}}'

**Comment by adamcirillo** [comment]
okay I've finally got nso to load with multiple commands had an issue with the escape character in the sed with needed // to fix and the ncs reload command to restart nso for it to pickup the command changes did not work but it was not needed to enable the web server which I thought it was in the NSO documentation. I'm planning to submit a PR for this. just to make sure i've got this right I add the .yml to netsim/tools and the documention would go into the docs/extool folder, is there anything else i would need to do?

**Comment by ipspace** [comment]
> okay I've finally got nso to load with multiple commands

Great job!

> I'm planning to submit a PR for this

That would be great. Thank you!

> just to make sure i've got this right I add the .yml to netsim/tools

... and whatever templates you need to the netsim/tools/nso folder

> and the documention would go into the docs/extool folder

Correct.

> is there anything else i would need to do?

An entry for 'extool/nso.md' in the toctree in 'docs/extools.md'
