### ISSUE TITLE
[BUG] Ansible task "copy cumulus config to /tmp/config.sh" fails when running netlab test libvirt

### ISSUE THREAD

**Issue by danohn** [ipspace/netlab#1633]
### Describe the bug

When running `netlab test libvirt` on a new Debian host, the Ansible task `copy cumulus config to /tmp/config.sh` fails with the following error:

```
TASK [copy cumulus config to /tmp/config.sh] **************************************************************************************************************
fatal: [s3]: FAILED! =>
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'
fatal: [s2]: FAILED! =>
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'
fatal: [s1]: FAILED! =>
  msg: 'Failed to get information on remote file (/tmp/config.sh): ansible-core requires a minimum of Python version 3.8. Current version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]'
```

The strange thing is that the Python version is 3.11.2 and not 3.7.3.

### To Reproduce

1. Install the latest Debian 12 on a host
2. `apt install python3-pip`
3. `pip install networklab --break-system-packages` (to install netlab globally and not within a venv)
4. `netlab install ubuntu ansible libvirt containerlab`
5. `netlab test libvirt`

### Expected behavior

The Ansible task `copy cumulus config to /tmp/config.sh` should pass

### Version

`netlab version 1.9.2`

**Comment by jbemmel** [comment]
Sounds similar to https://github.com/ipspace/netlab/issues/1590

**Comment by danohn** [comment]
Thanks @jbemmel !

**Comment by ipspace** [comment]
Looks like I have to push out a patch for (at least) the test scenario, and add a caveat for Cumulus Linux.

**Comment by ipspace** [comment]
Pushed out 1.9.2-post1, changing the devices in the initial tests from Cumulus Linux to Linux (which is Ubuntu 20.04 running Python 3.8). Not great (a total stopgap measure), but the best I could do without replicating the work we already did in dev branch.

@danohn: If you upgrade netlab with **pip3 install --upgrade networklab** you should get a version where the **netlab test libvirt** tests will pass (but using Linux VMs instead of Cumulus VX VMs)
