### ISSUE TITLE
Verify if Netlab validates plugin _required attributes

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1637]
https://github.com/ipspace/netlab/blob/743db8a57bf79dca3348c302f1575d6e4e759e4d/netsim/extra/node.clone/defaults.yml#L9

I added ```_required: True``` but it did not trigger Netlab to throw an error when specifying ```clone.start: X``` (i.e. clone parameters without the required ```count```)

**Comment by jbemmel** [comment]
See https://github.com/ipspace/netlab/pull/1638 - having "clone" instead of "count" doesn't trigger any errors

**Comment by ipspace** [comment]
It works in other cases. However, your code runs before the node attributes are validated and you remove the "clone" attribute after you're done, so nobody ever sees it.
