### ISSUE TITLE
Linux: Generalize the execution of provisioning scripts from container netns context

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1684]
Initial provisioning for Linux containers is done in ```ansible/tasks/linux/initial-clab.yml```, while remaining modules use ```ansible/tasks/deploy-config/linux-clab.yml```

My proposal is to include the functionality from ```ansible/tasks/linux/initial-clab.yml``` in ```ansible/tasks/deploy-config/linux-clab.yml```, and conditionally select ```ip netns``` from host or "native" execution within the container.

The condition could be: If the install script ends with "-clab.j2", use ```ip netns```
So we would have under ansible/templates/
* initial/linux-clab.j2
* lag/linux-clab.j2
* dhcp/linux.j2 ( i.e. regular )

**Comment by ipspace** [comment]
> The condition could be: If the install script ends with "-clab.j2", use `ip netns`

You might have forgotten all the daemons that are based on Linux, but after analyzing their implementation, it seems that your idea makes sense. Submit the proposed changes as a separate PR.
