### ISSUE TITLE
ebgp.multihop plugin does not handle ibgp_localas sessions correctly

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1685]
Context: https://github.com/ipspace/netlab/pull/1671

As the ```bgp.local_as``` parameter can be used on multihop sessions, the resulting session can end up as type ```localas_ibgp``` in case the ```bgp.local_as``` is set equal to the neighbor AS

The plugin does not handle this case correctly. In particular, the ```multihop``` value should be removed from such ibgp sessions

**Comment by ipspace** [comment]
> The plugin does not handle this case correctly.

That is correct.

> In particular, the `multihop` value should be removed from such ibgp sessions

And that is wrong.

In any case, submit the changes that you think will fix the problem as a separate PR.
