### ISSUE TITLE
OSPFv3 support for NX-OS, Cumulus and Nokia SR OS

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#220]
We need OSPFv3 support for most of the devices supported by netsim-tools (currently implemented: IOSv, IOS/XE, EOS, FRR). 

This is a nice opportunity for new contributors to get familiar with netsim-tools development process, let's wait a few days to see if there are any volunteers ;)

**Comment by ipspace** [comment]
In the meantime, @ssasso implemented OSPFv3 on VyOS (#221) and Junos vSRX (#224). The latter one is a picture-perfect example of how an "OSPFv3 on X" PR should look like

**Comment by jbemmel** [comment]
Nokia SR Linux templates now do have support for ospfv3: https://github.com/ipspace/netsim-tools/blob/dev/netsim/ansible/templates/ospf/srlinux.macro.j2#L9

**Comment by ipspace** [comment]
> Nokia SR Linux templates now do have support for ospfv3: https://github.com/ipspace/netsim-tools/blob/dev/netsim/ansible/templates/ospf/srlinux.macro.j2#L9

... and the OSPF module documentation reflects that 😊👍

**Comment by ipspace** [comment]
@ssasso I'm guessing Router OS 6 does not support OSPFv3, and it's in Router OS 7, so I'll remove Mikrotik from the list.

**Comment by ssasso** [comment]
Yes, let's remove ROS6 from the list...
IPv6 support in Router OS 6 is... $@!£&

**Comment by ipspace** [comment]
Added OSPFv3 support for Cumulus and Nexus OS
