### ISSUE TITLE
VRF support for Junos

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#227]
#225 added VRFs, L3 VRF interfaces, and VRF-aware routing protocols. The VRF configuration module currently supports Cisco IOS, IOS-XE and Arista EOS.

If anyone feels like implementing these features on other platforms please let me know and I'll write the developer docs to help you get started.

**Comment by willimei** [comment]
At the moment I am going to implement VRF Support for NXOS, because we need it for our lab.
I have started with adopting the Jinja2 templates from the IOS version.
Maybe you can point me to some other points where changes are needed (besides the topology-defaults.yml).

**Comment by ipspace** [comment]
@willimei: Thanks a million for investing your time into this. Opened #314 to track it, moving the discussion over there.

**Comment by ipspace** [comment]
Cisco Nexus OS support implemented in #321.

**Comment by ipspace** [comment]
Cumulus support in 683a76e945e9044eb5e984e3422cd8b507d0dad1, looks like nothing much will happen with SR OS.

Waiting for a Junos warrior ;)

**Comment by jbemmel** [comment]
May add SR OS support based on demand - am focusing on SR Linux for now

**Comment by ssasso** [comment]
Working on this for JunOS (both vSRX and vMX, of course).

**Comment by ipspace** [comment]
Implemented in #688
