### ISSUE TITLE
VLAN example has duplicate link

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#308]
See https://github.com/ipspace/netsim-tools/blob/eeb2fe7555f8bfc6394ee4c84521221430cd8eee/tests/topology/input/vlan-trunk-native.yml#L38

The s1-s2 link is modeled twice, with different representations

**Comment by ipspace** [comment]
Thanks for pointing it out, but that's on purpose.

The test case tries to cover many different scenarios, and one of them is a mismatch in trunk specification combined with native VLAN.

**Comment by ipspace** [comment]
Also, the test cases should not be used as end-user examples. We have https://github.com/ipspace/netsim-examples/tree/master/VLAN for that.

**Comment by jbemmel** [comment]
To support device implementers, it would help if the source repo at netsim-tools would contain an example showcasing the various use cases for VLANs. Like a compliance test for declaring 'vlan support'

**Comment by ipspace** [comment]
Totally agree. Will do... but I'll either get it done today or it will take a few days.
