### ISSUE TITLE
VLAN support for Junos

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#313]
If anyone feels like implementing VLAN module for any of these platforms you'd be most welcome ;)

Note: It might be a bit tricky -- this is not the ideal candidate for your first contribution to netsim-tools

**Comment by ipspace** [comment]
Junos "VLAN and bridging" documentation (so I won't have to Google for it again)

https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/topic-map/bridging-and-vlans.html

**Comment by ipspace** [comment]
Nexus OS support added in f7f3dfe

**Comment by ipspace** [comment]
Cumulus VLAN support added in bfbd9fe

**Comment by ssasso** [comment]
Working on this for JunOS (only vMX for now - vSRX seems to not support all the stuff).

**Comment by ipspace** [comment]
> Working on this for JunOS (only vMX for now - vSRX seems to not support all the stuff, need to study better how to differentiate between vMX and vSRX).

If nothing else, vSRX should support routed VLAN subinterfaces (so it could be used as a VLAN-aware router).

You could use `vmx.j2` and `vsrx.j2` VLAN templates, there are also per-device feature flags and per-platform quirks. In many cases it might make sense to have some shared code (like what we have between Cumulus and FRR) included in platform-specific part. You could use the same with quirks -- have shared routines in `junos.py` and platform-specific quirks in `vmx.py` and `vsrx.py`

**Comment by ipspace** [comment]
... on a tangential topic: CSR1000v is done (#687)

**Comment by ipspace** [comment]
Implemented in #688
