### ISSUE TITLE
Interface (node-to-link attachment) attributes are not checked

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#319]
e5e96141dd92c53c3bc2231369e63088d8e5ab20 successfully added support for `ifindex` interface attribute even though there's no related attribute defined in `attributes` part of topology defaults. Clearly we need a check of interface attributes ;)

**Comment by jbemmel** [comment]
vlan attributes are also not checked - 'role' is not listed as a valid attribute, but it is allowed and does affect the generated configuration
