### ISSUE TITLE
Avoid creating SVI interfaces for l2-only VLANs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#355]
Since SVI are L3 interfaces, can't we skip creating them when dealing with an L2-only VLAN ( i.e. vlan.mode == bridge )

On SR Linux I currently end up with unused irb interfaces e.g. in case of vlan-mixed-multiple.yml (vlan red on s1)

**Comment by ipspace** [comment]
This definitely makes sense and wouldn't be that hard to do. I'd have to check whether an SVI interface has any address family enabled before adding it.

Based on recent Dell10 experience I lost faith in assuming anything about how platforms should behave, so I'll use a device feature to tweak this behavior.

Also, keep in mind that unless we have an interface, we can't add a node to a neighbor list. Not sure whether that matters for L2-only nodes.

**Comment by ipspace** [comment]
While fixing #311 I realized we need these interfaces (even if they have no IP address) in the data model, so the best thing we could do is to set a flag to indicate the interface does not need to be created on the device, and then you can test that flag in the device configuration template.

The existing 'vlan.mode' attribute could serve as such a flag now that it's consistently set

```
{% if intf.virtual_interface is defined and intf.vlan.mode|default('') == 'bridge' %}
{# skip a layer-2-only VLAN interface #}
{% else %}
...
{% endif %}
```

Would that work for you?

**Comment by jbemmel** [comment]
I did notice that removing them breaks some assumptions in the way the data model gets populated.

I guess we can filter them out (though I think it might require type=='svi' and mode!='irb')

**Comment by ipspace** [comment]
> I guess we can filter them out (though I think it might require type=='svi' and mode!='irb')

I would check for `mode == 'bridge'` (plus whatever else is needed to identify SVI interface)

**Comment by jbemmel** [comment]
On SR Linux I map svi interfaces to irb interfaces, and we only need those for the case mode=='irb'.

In case of bridge only or route only, a regular physical interface (with mode=bridged or mode=routed) is sufficient
