### ISSUE TITLE
Replacing ebgp-local_as plugin with BGP attributes on Nokia SR OS, Dell OS10, VyOS

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#369]
The recent additions to BGP attributes (#366 and #365) allow us to implement IBGP-over-EBGP EVPN design without any extra evpn attributes or plugins -- the test case is here https://github.com/ipspace/netlab/blob/dev/tests/integration/evpn/vxlan-bridging-ibgp-over-ebgp.yml

It would probably make sense to migrate the current implementations on Nokia SR Linux, Dell OS10 and VyOS to the new attributes, all you have to do is to implement activation of IPv4 session based on **activate** neighbor attribute (see #366). No rush though, I can mark the platforms using the "old" method in the documentation before pushing out the next release.

**Comment by jbemmel** [comment]
PR https://github.com/ipspace/netlab/pull/372 adds srlinux support
