### ISSUE TITLE
Be more forgiving to devices that don't support tunable BGP address families yet

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#370]
The current code refuses to deploy a topology that includes FRR devices when using bgp.activate:
https://github.com/ipspace/netlab/blob/579d9904f602dfc8141e74f8e571e3ac5cd6554b/netsim/modules/bgp.py#L283

Could we turn this into a warning, and allow the user to deploy? There is a good chance that the default address families can work

**Comment by ipspace** [comment]
Well, I solved the FRR challenge ;) 8580a13e66cea5991b47656f088cadd8002deb72. More later...

**Comment by ipspace** [comment]
Now for the "could we turn this into a warning". TL&DR: No.

To start with, we don't have warnings yet, but it should be pretty easy to add them. However, now that we have **netlab up** doing all the hard work, we would have to stop that process between creating orchestration/automation files and deploying the lab and asking the user "hey, your topology has warnings, do you want to proceed?"

Next, assuming we check device features for a good reason, then we shouldn't respond to a non-compliant topology with a warning. It's pretty easy to deploy a totally broken IBGP-over-EBGP topology, and the error you don't like is there to stop someone from doing that unintentionally (and wasting time trying to figure it all out).

Finally, as **bgp.activate** doesn't have to be a global parameter, it's easy to create topologies in which some nodes use that attribute and some don't. Use **node_data** in **groups** if you don't like repeating yourself.

**Comment by jbemmel** [comment]
I did try using a group, but didn’t realize I had to use node_data

Could add a hint to the error that says you cannot use ‘activate’ under groups 

(somewhat inconsistent - why does one need node_data under a group, but not under a node?)

**Comment by ipspace** [comment]
> I did try using a group, but didn’t realize I had to use node_data
> Could add a hint to the error that says you cannot use ‘activate’ under groups

If anything, we could check the group attributes and reject unexpected ones (maybe hinting they might go into node_data)

> (somewhat inconsistent - why does one need node_data under a group, but not under a node?)

https://netsim-tools.readthedocs.io/en/latest/groups.html#setting-node-data-in-groups

Call it organic growth (because that sounds so much better than lack of foresight)
