### ISSUE TITLE
Support bgp.activate inside vrfs?

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#384]
Currently no 'bgp.activate' attribute is configured within vrfs.

To add: bgp.py module line 294
```
  activate_bgp_default_af(node,activate,topology)
  # Add
  if 'vrfs' in node:
    for vrf,vdata in node.vrfs.items():
      activate_bgp_default_af(vdata,activate,topology)
```

**Comment by ipspace** [comment]
Why would you ever want to do that? The only reason (so far) we had to add "activate" to support the stupid IBGP-over-EBGP setup.

Also, the next thing that would happen is someone saying "gee, I want to have different sessions in VRFs than in global routing table" and then "but I really need different session setup for each VRF". It's just not worth opening that snake pit.

**Comment by jbemmel** [comment]
For consistency - for me, VRFs are merely separate contexts, with much the same features as the 'default' VRF. I accidentally created a non-default VRF with a BGP session inside it, and noticed it doesn't currently work because of the above

For the SR Linux templates, I apply the same macro as the 'default' vrf to each additional ip-vrf. It stumbled on the missing 'activate' attribute

**Comment by ipspace** [comment]
> For consistency

Have you ever seen something implemented for consistency ;) JK...

> - for me, VRFs are merely separate contexts, with much the same features as the 'default' VRF. I accidentally created a non-default VRF with a BGP session inside it, and noticed it doesn't currently work because of the above

While that's true, they are usually used in different ways than the default routing table, and as I said, if we go down the path of "let's implement everything that's in the global table in VRFs" we will quickly get to the point where we'll have to implement those settings for individual VRFs. Not sure I want to be there.

Having said that, if someone finds a really good (and hopefully sane) use case for selecting AF activation within a VRF, we can obviously get it done. Until then, I'm closing this one.

> For the SR Linux templates, I apply the same macro as the 'default' vrf to each additional ip-vrf. It stumbled on the missing 'activate' attribute

Interestingly, I didn't encounter similar challenges on other platforms, but then I'm not calling the neighbor macro within the address family if the neighbor does not need to be activated . Why would I add an AF with a neighbor that's not used?

**Comment by jbemmel** [comment]
IOS:
* Default VRF: https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/bgp/ios.j2#L35
* Other VRF: https://github.com/ipspace/netlab/blob/dev/netsim/ansible/templates/vrf/ios.bgp.j2#L17

I'll change it to ignore a missing 'activate' attribute
