### ISSUE TITLE
CL NVUE does not have BGP "neighbor update-source" equivalent

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#389]
Here's another NVUE SNAFU: I can't find a way to configure **neighbor update-source** for IBGP sessions, so of course they don't come up. Looks like there's _absolutely no way_ to configure sane IBGP with NVUE. Interestingly, you can configure RR clients and such stuff.

I wonder whether anyone is using this stuff for real...

@petercrocker: Do we document that CL NVUE does not support IBGP and move on?

**Comment by ddutt** [comment]
@ipspace My recommendation: skip VUE. Just write out frr.conf and /etc/network/interfaces. It'll work with any version of CL< AFAIK, work with SONiC and any one else who uses FRR. You just need to know how to trigger the conf to take effect (systemctl restart frr OR something else that's platform specific)

**Comment by ddutt** [comment]
@ipspace : See my comment to another issue. Just manipulate frr.conf directly.

**Comment by ipspace** [comment]
> @ipspace My recommendation: skip VUE.

@ddutt Thank you. Just to be on the safe side, I started CL 5.2.0 lab with the old device type (**cumulus**) and of course it all works.

Will document how to do that.

> Just write out frr.conf and /etc/network/interfaces.

Can't do that, as netlab never generates the whole device configuration, so it has to rely on vtysh to do the merge.

> It'll work with any version of CL< AFAIK, work with SONiC and any one else who uses FRR. You just need to know how to trigger the conf to take effect (systemctl restart frr OR something else that's platform specific)

This shouldn't be a big deal in case anyone wants to tackle that.
