### ISSUE TITLE
Default ipv6 router advertisement interval

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#391]
Could be a parameter:
```
initial:
  ipv6:
    ra_interval: 30 # Default RA interval, in seconds
```

**Comment by ipspace** [comment]
There are at least a half-dozen IPv6 settings that could be tweaked on an interface. The proper place to implement them is probably a plugin along the lines of **ebgp.utils**.

I suspect **ipv6.options** might sound more serious than **ipv6.nerd-knobs** ;)

**Comment by jbemmel** [comment]
The reason I bring this up, is that the current templates contain basically hardcoded values for these intervals.

For SR Linux I initially opted to copy them, but I'm now thinking to leave the setting out and use platform defaults. I am not sure if the other platforms need some specific value configured - but if they do, I think a common variable like the above would be better than hardcoded values like "ipv6 nd ra-interval 5"

**Comment by jbemmel** [comment]
I've decided to remove the setting, and leave it as platform default: https://github.com/ipspace/netlab/pull/394/files#diff-3876b7141aa892b2b851d15e344fc0687b2d1b00aed62ce67939c5fde9716b1dR22

We could consider doing the same for other platforms (frr,cumulus)

**Comment by ipspace** [comment]
I think there's a reason it has to be enabled on those platforms (maybe because they don't have an equivalent of **ipv6 enable** interface configuration). Never found time to figure out the details though.
