### ISSUE TITLE
Installing as Python Package - not working for the first time

### ISSUE THREAD

**Issue by aegiacometti** [ipspace/netlab#41]
According to https://netsim-tools.readthedocs.io/en/latest/install.html#installing-a-python-package
Only `python3 -m pip install netsim-tools` is enough to install. But it is not installing the requirements.
![image](https://user-images.githubusercontent.com/16782779/136549488-035d9cd8-1f9f-4626-a8df-5a7a34724469.png)

If I fist install the requirements from https://github.com/ipspace/netsim-tools/blob/master/requirements.txt
It will work fine
`python3 -m pip install jinja2 pyyaml netaddr python-box`
`python3 -m pip install netsim-tools`

Notice that this happens only the first time, for the next installation there will be a wheels cache and it works without specifying the extra modules.

I think this could be a good heads-up for newcomers to the project.

I don't know yet how to fix that in the pip install setup, or maybe just add a comment in the installation guide would be enough.

**Comment by ipspace** [comment]
Fixed by 89ad83a07215a2d4435b6ccaf967e19cde394bcc. Pushed Python package to PyPi as -post1 version, so you'll get the correct package when doing **pip3 install netsim-tools==0.9.2**
