### ISSUE TITLE
Release 1.3.1: any showstoppers?

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#416]
I'm getting lost in a maze of twisty little commits, all alike. It's time to push out another release.

Is there anything you're still working on @jbemmel that you'd like to see in release 1.3.1? If not, then I'll just run a few FRR tests to make sure all integration test cases run as expected (and maybe port the FRR work to Cumulus Linux 4.x and add EVPN on Nexus OS if it keeps raining over the weekend).

**Comment by ipspace** [comment]
> For the native vlan, I think we may need to disallow `mode: route` and throw an error - if you agree, I can add that

Agree (based on discussion in #415), but we need to do that based on a device feature flag. Something like 'native_routed' which would allow routed native VLAN when set. Would you add that or should I?

> Also, there is an issue with using vrf.vrfidx as transit_evi: Different nodes may have different vrfidx for a given vrf

**vrfidx** is locally significant, so there's that. Now we have **id** that is globally unique (even across node-local VRFs). Hope that works for you.

**Comment by ipspace** [comment]
Added `native_routed` feature flag in 83bb095514b2af944f201f3fba0e8de2c519f77e -- I was already tinkering with that part of the code, and knew exactly where the check would have to go.

**Comment by jbemmel** [comment]
Submitted https://github.com/ipspace/netlab/pull/441 to fix checking the flag early enough in the transformation process

**Comment by ipspace** [comment]
#447 is a showstopper - would love to get this fixed before the VLAN documentation gets pushed to the master branch.

**Comment by ipspace** [comment]
Also, #452 is annoying when you're using netlab for something else but starting the lab.

**Comment by ipspace** [comment]
#441 will wait for the next release (we have to have another complex discussion), #447 and #452 are fixed. Off we go...

**Comment by ipspace** [comment]
Release 1.3.1 has been merged into master and pushed to PyPi. Thanks a million for all the PRs and issues ;)
