### ISSUE TITLE
first test run - vagrant up box file not found

### ISSUE THREAD

**Issue by aegiacometti** [ipspace/netlab#42]
Hello again, while testing following this link https://netsim-tools.readthedocs.io/en/latest/labs/virtualbox.html#testing-the-installation

When I run `vagrant up` I get this error. It seems logical because the file name does not exist, maybe is the other "box" filename?

![image](https://user-images.githubusercontent.com/16782779/136585390-cd62491a-531f-41e4-98d3-b649e5b35bf5.png)

Any idea?

**Comment by ipspace** [comment]
Assuming the test procedure crashed, could you post Vagrantfile it created (just to be on the safe side)?

**Comment by aegiacometti** [comment]
Thanks master 😉
