### ISSUE TITLE
Undocumented vlan.role attribute

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#440]
https://github.com/ipspace/netlab/blob/bc81f8c3c935f74c02124deaef6df77461fcbaca/netsim/augment/links.py#L269

The 'role' attribute may affect a vlan via https://github.com/ipspace/netlab/blob/dev/netsim/modules/vlan.py#L191
It effectively takes precedence over any 'pool' attribute

```vlan.pool``` is only used to select an alternative addressing pool, while ```link.role``` has wider implications ( e.g. becomes part of 'description' field on some devices )

Options:
1. Document/allow ```vlan.role```
2. Deprecate ```vlan.pool```, replace with ```vlan.role```
3. Rename ```vlan.pool``` to ```vlan.role``` internally
4. Other?

**Comment by ipspace** [comment]
Will be addressed in #445
