### ISSUE TITLE
LAN IP addressing duplicate IP test case marked as 'valid'

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#444]
https://github.com/ipspace/netlab/blob/21d371dc07c53a28ed459d4fcee8029b49110cc9/tests/topology/input/addressing-lan.yml#L66

While rewriting the logic for IP address assignments on LAN links, my new code flagged this .5 address as duplicate (correctly I believe)
I would propose to:
1. Change "5" into "6" to get a valid case
2. Create an error case covering this case

**Comment by ipspace** [comment]
I really don't care about the particulars of that one link, it's supposed to be testing different address assignments. If you feel better changing "5" into "6", go for it.

As for "checking for duplicate IP addresses" -- you want to enable netlab users to build stuff like IBGP-over-EBGP, or disable IPv4 address family on IPv4 BGP session, and now you want to prevent those same users from statically assigning duplicate IP addresses? There's something wrong with this picture 🤣🤣
