### ISSUE TITLE
VLAN: document virtual link creation

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#445]
> vlan attributes are also not checked - 'role' is not listed as a valid attribute, but it is allowed and does affect the generated configuration

_Originally posted by @jbemmel in https://github.com/ipspace/netlab/issues/319#issuecomment-1244286265_

Obviously I have to document how the virtual links are created out of VLAN trunks, and what attributes get assigned to them. That might also answer a few other outstanding issues.

**Comment by ipspace** [comment]
Updated VLAN module documentation, draft version @ https://github.com/ipspace/netlab/blob/vlan-doc/docs/module/vlan.md

In particular:

* Added "deployment recommendation" section (not that anyone would heed it)
* Explained that all link attributes (including **role**) can be used as VLAN attributes
* Tried to stress a few times that **access** or **native** VLANs with **mode: route** make no sense

@jbemmel: If you feel I missed something, please let me know.

**Comment by jbemmel** [comment]
Given that 'native' is only valid in combination with 'trunk', wouldn't it make more sense to model it like this?
```
links:
- r1:
  r2:
  vlan.trunk: [ some-other-vlan, native-vlan ]
  vlan.trunk.native: native-vlan
```

Note that when a routed vlan is used as access vlan, it uses the 'p2p' addressing pool. Any custom 'pool' attribute is ignored

**Comment by ipspace** [comment]
> Given that 'native' is only valid in combination with 'trunk', wouldn't it make more sense to model it like this?
> 
> ```
> links:
> - r1:
>   r2:
>   vlan.trunk: [ some-other-vlan, native-vlan ]
>   vlan.trunk.native: native-vlan
> ```

Yeah, I agree that would make more sense, but keep in mind that those are really:

```
vlan:
  trunk: [ a,b,c ]
```

and

```
vlan:
  trunk:
    native: a
```

... and those two things don't mix well.

> Note that when a routed vlan is used as access vlan, it (currently) uses the 'p2p' addressing pool. Any custom 'pool' attribute is ignored (some might call this a bug/issue)

Yep, that's #430 all over again.

**Comment by jbemmel** [comment]
Then maybe
```
links:
- r1:
  r2:
  vlan.trunk: 
    members: [ some-other-vlan, native-vlan ]
    native: native-vlan
```

```groups``` have members, and isn't a trunk simply a group of vlans on a link?

**Comment by ipspace** [comment]
And why should we change a working implementation just because an alternate data structure looks nicer? VLANs are hard enough already.
