### ISSUE TITLE
Disable a routing protocol per VRF or interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#446]
Based on #443 - we need a mechanism to disable a routing protocol (OSPF, IS-IS, BGP...) for an interface or for a whole VRF.

While netlab does a good job handling most of the designs (automatically pruning routing protocols based on adjacent node capability), there might be an edge case where you might not want to have EBGP sessions across an interface even though the attached devices are BGP speakers, or might not want an interface being part of an OSPF process (even though marking it **passive** would do the trick).

A crazy scenario that immediately comes to mind is a VRF Lite case where you'd want to run OSPF across one L3 domain and BGP across another one. Not that I would ever consider doing something along these lines, but the amount of weirdness found in the wild never stops surprising me.

**Comment by jbemmel** [comment]
The vrf module has an "informal" ```ospf.activate``` parameter; it is [documented](https://github.com/ipspace/netlab/blob/dev/docs/module/vrf.md#interaction-with-routing-protocols) but not listed in topology-defaults as a valid (vrf) attribute

We could do something similar for bgp and isis, instead of ```bgp: False``` as proposed by https://github.com/ipspace/netlab/pull/443

**Comment by ipspace** [comment]
Looking at some other code, it seems we can already set **some_protocol: False** on links/interfaces (see `tests/topology/input/vrf-igp.yml`). Have to check how generic that is -- maybe all we need is to a check in the BGP neighbor processing routing.

**Comment by ipspace** [comment]
> The vrf module has an "informal" `ospf.activate` parameter; it is [documented](https://github.com/ipspace/netlab/blob/dev/docs/module/vrf.md#interaction-with-routing-protocols) but not listed in topology-defaults as a valid (vrf) attribute

To be pedantic -- we have `ospf.active` and `bgp.activate` ;), but yeah, maybe we should rename that to `ospf.enable`.

`ospf.active` does not have to be listed as a valid VRF attribute as we don't check VRF module attributes yet... but maybe we should.

**Comment by jbemmel** [comment]
I see how this works per interface, but does it include the ability to disable it per vrf?
It also seems this feature isn't documented yet?

**Comment by ipspace** [comment]
> I see how this works per interface, but does it include the ability to disable it per vrf?

What does your minimal test topology say? ;)

> It also seems this feature isn't documented yet?

https://netsim-tools.readthedocs.io/en/dev/module/routing.html#routing-disable

Guess we could add a few links to that section ;))

**Comment by jbemmel** [comment]
I would like to see the following:
```
vrf.bgp: False
```
and
```
vrfs:
 a:
  bgp: False
 b:
```

When I said "seems" I meant that it's not found in or referenced from the bgp module documentation, which where I'd think users would likely start if they're looking to disable bgp

**Comment by ipspace** [comment]
> I would like to see the following supported:

Yeah, I know, you would like to see many things supported. When that results in an intricate web of dependencies and disrupting one thing breaks three others your answer is "if you are not breaking things you are not moving fast enough". Fortunately, we're not a vendor competing on RFP features.

I will look at how much work it would be to have **protocol: False** at an individual VRF level, otherwise you'll just have to cope with the sad reality that it's good enough to have one way of configuring things.

> When I said "seems" I meant that it's not found in or referenced from the bgp module documentation, which is where I'd think users would likely start if they're looking to disable bgp

So this is not good enough?

https://netsim-tools.readthedocs.io/en/dev/module/bgp.html#interface-level-parameters

Fun fact: BGP is probably the only module where this functionality is explicitly described.

**Comment by ipspace** [comment]
Closed for good. Don't mention it again ;)
