### ISSUE TITLE
Deprecating 'role' link attribute as address pool selection mechanism

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#447]
@jbemmel made a very valid point: dealing with link **role** and VLAN **pool** (but also **role**) is frustrating.

I could document the differences, but it's much better to fix the confusion, deprecating **role** and introducing **pool** link attribute:

* The **pool** attribute (VLAN or link) would have the same effects as the current **role** attribute. The value would **have to be** a valid address pool (whereas the current **role** attribute is just a hint).
* The **role** attribute would stay there, as we need it sometimes to indicate link type (_stub_ and _external_ immediately come to mind). It would also continue functioning as an address pool hint until we decide the deprecation grace period is over.

The address pool selection logic would obviously be:

* If a VLAN or link has **pool** attribute, check that it refers to a valid address pool (and fail otherwise) and use it
* If there's no **pool** attribute, but the **role** attribute happens to refer to a valid address pool, use that
* Otherwise, use the default pool.

@jbemmel @ssasso @petercrocker: any additional thoughts or objections?

**Comment by ipspace** [comment]
Note to self: if we go ahead with this, add **role** to `vlan_link_attr_copy` in `vlan.py#34`

**Comment by ipspace** [comment]
Last call @jbemmel @ssasso @petercrocker: any objections to adding **pool** attribute to links while retaining backward compatibility with **role** attribute?

**Comment by jbemmel** [comment]
There are corner cases like when “role” is set internally in the code; I had a pool called “external” and the results were non-intuitive 

I think throwing an error when finding “role” on a vlan may be better, instead of fuzzy matching on address pools. It was never a valid attribute, just not enforced 

So yes, let’s add pool to links and add a warning when role is used to match a pool
