### ISSUE TITLE
'Releases' for ipspace/netlab shows 1.1.3 as latest

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#459]
Front page at https://github.com/ipspace/netlab shows only 1 release, 1.1.3 from February 19 2022

I think you may need to do https://github.com/ipspace/netlab/releases/new?tag=release_1.3.1

**Comment by ipspace** [comment]
Thank you for pointing this out. I tried using releases, and hoped I'd get a useful changelog, but things didn't exactly pan out as expected.

As I'm not using that mechanism, I deleted the only release to ensure I'm not confusing anyone.
