### ISSUE TITLE
VRF OSPF area is not used as the default OSPF area for VRF interfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#494]
The **ospf.area** parameter is set within a VRF is used on the VRF loopback interface, but not on other VRF interfaces. Global **ospf.area** is used on those.

**Comment by ipspace** [comment]
@jbemmel FYI: had to add two more module hooks (one is really needed, the other one is just for consistency), resulting in the longest commit message I've written so far ;)

**Comment by jbemmel** [comment]
Are you aware that the code still contains various calls to hooks that are not present anywhere?

This call to ```pre_node_transform``` for example: https://github.com/ipspace/netlab/blob/dev/netsim/augment/main.py#L48

```
jeroen@jvm:~/srlinux/netlab/tests$ grep -r "pre_node_transform" ../netsim/
../netsim/augment/main.py:  augment.plugin.execute('pre_node_transform',topology)
../netsim/augment/main.py:  modules.pre_node_transform(topology)
grep: ../netsim/augment/__pycache__/main.cpython-310.pyc: binary file matches
../netsim/modules/__init__.py:def pre_node_transform(topology: Box) -> None:
../netsim/modules/__init__.py:  module_transform("pre_node_transform",topology)
../netsim/modules/__init__.py:  node_transform("pre_node_transform",topology)
../netsim/modules/__init__.py:  link_transform("pre_node_transform",topology)
```

Similar for ```pre_link_transform``` https://github.com/ipspace/netlab/blob/dev/netsim/augment/main.py#L56

**Comment by ipspace** [comment]
I know, but sometimes they do come handy, and there might be more cases like that. Please note that we have three forms of each hook as a developer convenience -- one of them is called as-is, the other one iterates over all nodes, the third one iterates over all links.
