### ISSUE TITLE
Arista EOS: Don't configure MPLS LDP on interfaces without a valid IPv4 address

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#497]
Arista EOS mpls.ldp template configures "mpls ldp interface" even on interfaces without a valid IPv4 address.

Check whether that's a data model challenge (LDP should not be enabled on interfaces without an IPv4 address) or a template error.

**Comment by jbemmel** [comment]
data model: https://github.com/ipspace/netlab/blob/dev/netsim/modules/mpls.py#L45

Code should check for 'ipv4' in intf, and skip interfaces without ipv4 enabled

**Comment by ipspace** [comment]
Thank you, fixed
