### ISSUE TITLE
Release 1.4 plans

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#510]
I'm thinking about a few radical changes to the data model. They would not break any major functionality, but are significant enough that I don't want them in 1.3.x release but would prefer 1.4 release (with a warning in README.md saying "this might not be the most stable release ever")

Those changes include VNI allocation (#509), IPAM redesign to address #455 and EVPN redesign to include MPLS support (#511).

There are still a few bugs I'd like to see fixed in 1.3.2, and Stefano would probably like to see RouterOS 7 shipped ASAP, so I'd suggest we split the 1.4 features into a separate **dev-1.4** branch.

* All the truly new stuff would go into 1.4 branch.
* Bug fixes and minor changes would be applied to **dev** branch which would eventually become 1.3.2 (and we won't go beyond that apart from critical fixes)
* I would periodically rebase **dev-1.4** from **dev** (which would bring in all the bug fixes)

Any suggestions or objections @jbemmel @ssasso?

**Comment by jbemmel** [comment]
Just submitted https://github.com/ipspace/netlab/discussions/513 suggesting ```evpn.as``` for EVPN EBGP use cases - minor change that shouldn't impact most users, but the conceptual design of autonomous systems and how they relate to EVPN and VRFs could use some elaboration and tweaking

**Comment by ipspace** [comment]
@ssasso @jbemmel: Release 1.3.2 is out, and I already started working on #455.

Please submit new work/features PRs against dev-1.4 branch and important bug fixes against dev branch. I will push out `1.3.2-postX` releases if needed.

**Comment by ipspace** [comment]
Bug fixes accumulated during this week were pushed out, **dev-1.4** has been merged into **dev**. We're working on 1.4 from now on ;)
