### ISSUE TITLE
EVPN IRB models

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#562]
Have to do "a bit" more reading and a few hands-on tests, but it looks like we might have to support three modes of EVPN IRB:

* Asymmetric -- no transit VNI or L3 wire
* Symmetric -- transit VNI/L3 wire used for RT5 prefixes
* Host routes -- symmetric IRB with RT2 IP addresses turned into VRF host routes

We could add a VRF attribute **evpn.irb** with three valid values: _asymmetric_, _symmetric_ and _hosts_. These settings would trigger a ton of things that we still have to figure out. For example:

* We need to create VLAN interfaces for every EVPN-enabled VLAN in a VRF on every node using that VRF _even when that VLAN is not used on the node_
* We should enable IGP over stretched subnets in asymmetric mode _if there are other routers attached to the same subnet(s)_ but not in symmetric mode.

I'm positive there will be other gotchas we'll discover along the way. Any thoughts on this @jbemmel @ssasso @ddutt?

**Comment by jbemmel** [comment]
RFC9135 [defines](https://www.rfc-editor.org/rfc/rfc9135.html#name-control-plane-operation) a control plane procedure for symmetric IRB which involves 2 RTs per type 2 route. I'm guessing this may be what you call "host routes" symmetric IRB flavor?

SR Linux does not support that - it only uses a single RT and type 5 routes (RFC9136)

FRR has a feature called [EVPN Overlay Index Gateway IP](https://docs.frrouting.org/en/latest/bgp.html#evpn-overlay-index-gateway-ip) for recursive RT5 resolution following RFC9136.  It is supported for *asymmetric* routing model only

In all the above cases, what I think we need support for (perhaps more), is anycast gateways (https://github.com/ipspace/netlab/pull/551)

**Comment by ipspace** [comment]
> RFC9135 [defines](https://www.rfc-editor.org/rfc/rfc9135.html#name-control-plane-operation) a control plane procedure for symmetric IRB which involves 2 RTs per type 2 route. I'm guessing this may be what you call "host routes" symmetric IRB flavor?

Yes. Have to reach that RFC one of these days ;)

> SR Linux does not support that - it only uses a single RT and type 5 routes (RFC9136)

Noted. There are probably other platforms out there doing the same -- the more I'm dealing with EVPN, the more I believe calling it "SIP of networking" was the right call.

> In all the above cases, what I think we need support for (perhaps more), is anycast gateways (#551)

Absolutely agree. We'll get there ;) I'm just jotting down things that might have to be done (or not).

**Comment by ssasso** [comment]
> * Symmetric -- transit VNI/L3 wire used for RT5 prefixes
> * Host routes -- symmetric IRB with RT2 IP addresses turned into VRF host routes

Couldn't we "embed" these two into the same functionality (*symmetric irb*), and let the "template developer" to define how to handle them?

**Comment by ipspace** [comment]
The implementation (at least for the VXLAN world) turned out to be surprisingly simple, and in the MPLS world we assume symmetric IRB.

I don't think we want to go down the infinitely branching paths of various EVPN deployment models for the moment, but of course we could do whatever extra stuff with plugins ;)
