### ISSUE TITLE
Creating VLAN interfaces

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#563]
I always assumed life was simple and we could create VLAN interfaces for every VLAN on a box even when it's a pure L2 VLAN and the interface has no configuration. Turns out I was wrong (no surprise there) -- Arista EOS does not survive having VLAN interfaces with EVPN/MPLS VLAN bundles.

We will also encounter other scenarios where we need VLAN interfaces even though we don't use a VLAN on any other interface in the node, for example VXLAN-to-VXLAN routing or asymmetric IRB.

Looks like we have to add another VLAN attribute that controls the creation of VLAN interfaces, for example **interface** (in **vlans** entries) with valid values:

* **never** (don't create a VLAN interface, fail when used on a VLAN with **mode** not set to **bridge**)
* **when-used** (default value, existing behavior)
* **always** (always create a VLAN interface if the VLAN is present in node data)

Any thoughts on this one @jbemmel @ssasso?

**Comment by jbemmel** [comment]
I'm thinking conceptually it may be easier to ask users to associate vlans with a virtual loopback interface if there is a need to create an interface. That could be handled with existing code

Regarding removing l2-only svis: https://github.com/ipspace/netlab/issues/355

**Comment by ipspace** [comment]
> I'm thinking conceptually it may be easier to ask users to associate vlans with a virtual loopback interface if there is a need to create an interface. That could be handled with existing code

I don't get it, could you tell me more?

> Regarding removing l2-only svis: #355

I knew there was something... thank you! So we'd have to remove the SVI interfaces at the very end of the transformation process (like I do in _EOS device quirks_ for VLAN bundles) and just ignore the fact that **neighbors** list on other nodes contains invalid interface names.

In any case, the only reason (I found so far) not to create VLAN interfaces seems to be the EOS VLAN bundle over MPLS.

**Comment by jbemmel** [comment]
I mean something like this: https://github.com/ipspace/netlab/pull/571

**Comment by ipspace** [comment]
OK, assuming that you don't like an extra nerd knob (but I have a funny feeling we'll end up creating it anyway ;):

* We could stay with default behavior, and use _device quirks_ to remove the interfaces when needed (the only known use case: EVPN/MPLS VLAN bundles on Arista EOS, and it's already implemented as a quirk)
* We will need VXLAN endpoints with IP addresses, and we could say "we'll create VLAN interfaces _for all VLANs mentioned on a box_". EVPN configuration module could then pull all VLANs in a VRF into node **vlans** dictionary and the rest would happen automatically.

However, there's another nasty question: **what do we create?**

On **switch** platforms, the answer is simple: we need **vlan{vlan.id}** interface with an IP address and everything else happens automatically.

What about routers? How would you model that on a router? Is a VLAN interface (generated from **svi_interface_name**) what's needed? That would work on FRR, but what about SR Linux, SR OS or RouterOS? Fortunately I don't have to deal with IOSv or CSR -- one doesn't support VXLAN, and what the other does with VLANs is so crazy that I ran away.

@jbemmel @ssasso: feedback highly appreciated before I go and hack something together.

**Comment by jbemmel** [comment]
SR Linux:
* vlan.mode == 'bridge' -> regular interface type 'bridge', no IP
* vlan.mode == 'irb' -> subinterface on "irb0" interface, with an IP. Supports anycast gateway too
* vlan.mode == 'route' -> regular interface type 'route' (no anycast gateway support here)

For the asymmetric IRB case of EVPN, we'd create subinterfaces on irb0 for any vlans (mode != bridge) that are missing, associated with a mac-vrf with the evpn vni of the missing vlan, and with the ip-vrf that the vlan belongs to

SR OS:
* vlan.mode == 'bridge' -> sap/port in 'access' mode
* vlan.mode == 'irb' -> R-VPLS service with an ip interface in a VPRN
* vlan.mode == 'route' -> sap/port directly associated with VPRN or base router context, no VPLS

For the asymmetric IRB case of EVPN, we'd create a R-VPLS service for each vlan (mode != bridge) that is missing (limit: max 8 per VPRN)

**Comment by ipspace** [comment]
Thank you. Will hack together something along the lines of "create fake vlan_member links for the VLANs present in **nodes._node_.vlans** dictionary but having no attachment to the node, and then let's see what the configuration templates will do ;)

**Comment by ipspace** [comment]
In the end, things turned out simpler than I thought they would be: I decided to create VLAN interfaces for all IRB VLANs present in node **vlans** dictionary.

* It doesn't make sense to create VLAN interfaces for L2-only VLANs. What would you do with such interfaces?
* It doesn't make sense to create VLAN interfaces for routed VLANs -- they should terminate on physical subinterface
* Don't like the extra VLAN interfaces? Don't stuff VLANs into node VLAN dictionary ;))

VXLAN-to-VXLAN router-on-a-stick integration test case works beautifully with EOS and FRR (proving that the correct data is generated for **l3-switch** and **router**) but fails miserably on Cumulus VX which uses VLAN-aware bridge. Will open a separate case for that one.
