### ISSUE TITLE
Allow to run containerlab with different runtime flag

### ISSUE THREAD

**Issue by q2dg** [ipspace/netlab#586]
Thanks!

**Comment by ssasso** [comment]
Hello @q2dg, **netlab** is only a consumer of containerlab...
I think you should ask your "feature request" directly to the containerlab team @ https://github.com/srl-labs/containerlab

**Comment by q2dg** [comment]
Thanks for pointing out! 
But containerlab is already compatible from 0.30 version: https://github.com/srl-labs/containerlab/releases/tag/v0.30.0

**Comment by ssasso** [comment]
Ok, so can you please give us more info on what you think should be the requirement on netlab for supporting this?

**Comment by ssasso** [comment]
I guess it's just a matter of running containerlab with the proper runtime flag.
(https://containerlab.dev/cmd/deploy/#runtime)

@q2dg can you verify if a netlab clab output file works just fine with that? (I'm guessing you already have an environment where both podman and netlab are installed)

**Comment by q2dg** [comment]
Yes, it works!!

**Comment by jbemmel** [comment]
There is already code for 'runtime' https://github.com/ipspace/netlab/blob/dev/netsim/templates/provider/clab/clab.j2#L44.
May not be documented (and currently not explicitly modeled as an allowed node attribute) but try:
```
nodes:
 r1:
  runtime: podman # ( should really be 'clab.runtime' )
```

**Comment by q2dg** [comment]
Thaks. It works!
So I'll close this issue, if you don't mind
