### ISSUE TITLE
OSPF routing over VXLAN doesn't work on Cumulus VX

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#591]
For whatever reason, the `vxlan/vxlan-router-stick.yml` integration test case doesn't work with Cumulus VX. Must be some quirk in the VLAN-aware bridge setup as FRR works great.

**Comment by ipspace** [comment]
Red herring. S1 had IP addresses on VLAN interfaces and participated in OSPF. Now I have to figure out why OSPF didn't work between S1 and ROS ;)

**Comment by jbemmel** [comment]
MTU?

**Comment by ipspace** [comment]
We had MTU issues between containers and VMs, but that shouldn't be the case between boxes using newly-created VXLAN interfaces on the same software platform. In any case, I'm not touching Cumulus NVUE any more, and it doesn't have VXLAN support.

That missing **mode: bridge** broke the topology in so many different ways, and I don't feel like exploring that cesspool.

**Comment by ipspace** [comment]
Just created an OSPF-over-VXLAN integration test case and it works fine with Cumulus. Thanks for the suggestions!
