### ISSUE TITLE
Support for IOSvL2

### ISSUE THREAD

**Issue by Kircheneer** [ipspace/netlab#6]
I'm having problems getting a simple IOSv topology to work. I'm using the `vios_l2-adventerprisek9-m.03.2017.qcow2` image file. When I `virsh console` into the VMs I get normal output and I can interact with the CLI just fine. No IP address is configured on any interface though.

Contents of topology.yml:
```yaml
➜  netsim-tools git:(master) ✗ cat topology.yml 
defaults:
  device: iosv

nodes:
- name: s1
- name: s2
```

Output of `vagrant up` (leaving it run for a couple of minutes although it gets stuck after a short couple of seconds):

```
(venv) ➜  netsim-tools git:(master) ✗ vagrant up
Bringing machine 's1' up with 'libvirt' provider...
Bringing machine 's2' up with 'libvirt' provider...
==> s1: Checking if box 'cisco/iosv' version '12345' is up to date...
==> s2: Checking if box 'cisco/iosv' version '12345' is up to date...
==> s2: Creating image (snapshot of base box volume).
==> s2: Creating domain with the following settings...
==> s2:  -- Name:              netsim-tools_s2
==> s2:  -- Domain type:       kvm
==> s2:  -- Cpus:              1
==> s2:  -- Feature:           acpi
==> s2:  -- Feature:           apic
==> s2:  -- Feature:           pae
==> s2:  -- Memory:            512M
==> s2:  -- Management MAC:    08-4F-A9-00-00-02
==> s2:  -- Loader:            
==> s2:  -- Nvram:             
==> s2:  -- Base box:          cisco/iosv
==> s2:  -- Storage pool:      default
==> s2:  -- Image:             /var/lib/libvirt/images/netsim-tools_s2.img (2G)
==> s2:  -- Volume Cache:      default
==> s2:  -- Kernel:            
==> s2:  -- Initrd:            
==> s2:  -- Graphics Type:     vnc
==> s2:  -- Graphics Port:     -1
==> s2:  -- Graphics IP:       127.0.0.1
==> s2:  -- Graphics Password: Not defined
==> s2:  -- Video Type:        cirrus
==> s2:  -- Video VRAM:        9216
==> s2:  -- Sound Type:	
==> s2:  -- Keymap:            en-us
==> s2:  -- TPM Path:          
==> s2:  -- INPUT:             type=mouse, bus=ps2
==> s1: Creating image (snapshot of base box volume).
==> s1: Creating domain with the following settings...
==> s1:  -- Name:              netsim-tools_s1
==> s1:  -- Domain type:       kvm
==> s1:  -- Cpus:              1
==> s1:  -- Feature:           acpi
==> s1:  -- Feature:           apic
==> s1:  -- Feature:           pae
==> s1:  -- Memory:            512M
==> s1:  -- Management MAC:    08-4F-A9-00-00-01
==> s1:  -- Loader:            
==> s1:  -- Nvram:             
==> s1:  -- Base box:          cisco/iosv
==> s1:  -- Storage pool:      default
==> s1:  -- Image:             /var/lib/libvirt/images/netsim-tools_s1.img (2G)
==> s1:  -- Volume Cache:      default
==> s1:  -- Kernel:            
==> s1:  -- Initrd:            
==> s1:  -- Graphics Type:     vnc
==> s1:  -- Graphics Port:     -1
==> s1:  -- Graphics IP:       127.0.0.1
==> s1:  -- Graphics Password: Not defined
==> s1:  -- Video Type:        cirrus
==> s1:  -- Video VRAM:        9216
==> s1:  -- Sound Type:	
==> s1:  -- Keymap:            en-us
==> s1:  -- TPM Path:          
==> s1:  -- INPUT:             type=mouse, bus=ps2
==> s2: Creating shared folders metadata...
==> s2: Starting domain.
==> s1: Creating shared folders metadata...
==> s1: Starting domain.
==> s2: Waiting for domain to get an IP address...
==> s1: Waiting for domain to get an IP address...
```

I've searched the web for Vagrant being stuck on this messages but couldn't find anything that relates to this.

**Comment by ipspace** [comment]
I'm having problems getting a simple IOSv topology to work. I'm using the vios_l2-adventerprisek9-m.03.2017.qcow2 image file. When I virsh console into the VMs I get normal output and I can interact with the CLI just fine. No IP address is configured on any interface though.

Looks like you built your own Vagrant boxes. Does your box have ip address dhcp configured on the first (management) interface? Did you use the build recipe I recommended in netsim-tools documentation?

Also, did you use my setup for the vagrant-libvirt bridge? https://github.com/ipspace/netsim-tools/blob/master/netsim/templates/provider/libvirt/vagrant-libvirt.xml - it shouldn’t matter at this point, but will become important once you get the IP addresses assigned to the management interfaces.

Best, Ivan

**Comment by Kircheneer** [comment]
I used [this](https://codingpackets.com/blog/cisco-iosv-vagrant-libvirt-box-install/) for building the boxes although from your response I can tell that I missed at least the bit with the `ip address dhcp`, but more importantly all of the bootstrap configuration. Pardon my ignorance but from your comment it sounds like I could have gotten ready-made boxes from some place - is that correct?

Anyway from what I can tell this is a user error. Thank you for your help!

**Comment by ipspace** [comment]
You probably missed “wr mem” at the end of config.

**Comment by tepene** [comment]
I'm a bit late to the party ;) but how can we configure L3 functionality on the Gig0/0 interface on a `vios_l2-adventerprisek9-m` box?

I can't configure `vrf forwarding` nor `ip address dhcp`

![image](https://github.com/user-attachments/assets/43ad2050-564d-4077-a574-5e5e52025b4d)

i tried it with a dedicated vlan interface, which works during the box creation but when using the box in netlab the ip address does not get assigned and the device is not manageable.

**Comment by ipspace** [comment]
Ah, only now have I realized @Kircheneer wanted to use IOSvL2 image. It seems that one is so different from the regular IOSv image that I wouldn't expect it to work out-of-the-box.

Anyway, the first hurdle is the IP address on the management interface (ignoring for the moment that it seems like IOSvL2 does not support VRFs) -- you MUST get an IP address assigned via DHCP. After you figure out how to do that we can move to the next hurdle ;)

**Comment by tepene** [comment]
Well, 

I created a `cisco/iosv` box with `netlab libvirt package iosv vios_l2-adventerprisek9-m.ssa.high_iron_20200929.qcow2` and  used the [Building a Cisco IOSv Vagrant Libvirt Box](https://netlab.tools/labs/iosv/) configuration as a base and changed the interface parts as follows.

```
interface Vlan1
 description vagrant-management
 vrf forwarding MGMT
 ip address dhcp
 no shutdown
!
interface GigabitEthernet0/0
 description vagrant-management
 switchport access vlan 1
 switchport mode access
 negotiation auto
 no shutdown
!
```

With this I get an address via DHCP
![image](https://github.com/user-attachments/assets/7dff8434-56dd-405b-b348-e01eb21fabe2)

and routing via MGMT VRF looks good as well
![image](https://github.com/user-attachments/assets/78465815-3aef-4f1d-abc7-be49b9198383)

So far so good, what else needs some modification?

**Comment by DanPartelly** [comment]
Try this below for Gb0/0 (in addition to SSH config and EM applets needed ) . L2 images are workable, but they need proper labeling in netlab, and proper support might need some more involved modifications to how they are treated. 

vrf definition Mgmt-intf
address-family ipv4
exit-address-family
exit

interface GigabitEthernet0/0
shutdown
no switchport
vrf forwarding Mgmt-intf
ip address dhcp
no cdp enable
no lldp transmit
no lldp receive
no shutdown
exit

**Comment by tepene** [comment]
> Try this below for Gb0/0 (in addition to SSH config and EM applets needed ) . L2 images are workable, but they need proper labeling in netlab, and proper support might need some more involved modifications to how they are treated.
> 
> vrf definition Mgmt-intf address-family ipv4 exit-address-family exit
> 
> interface GigabitEthernet0/0 shutdown no switchport vrf forwarding Mgmt-intf ip address dhcp no cdp enable no lldp transmit no lldp receive no shutdown exit

As shown in https://github.com/ipspace/netlab/issues/6#issuecomment-2318174576 on the `vios_l2-adventerprisek9-m` image you can't configure `vrf forwarding` on the Gi0/0 interface.

**Comment by DanPartelly** [comment]
> As shown in [#6 (comment)](https://github.com/ipspace/netlab/issues/6#issuecomment-2318174576), on the `vios_l2-adventerprisek9-m` image you can't configure `vrf forwarding` on the Gi0/0 interface.

![vrf2](https://github.com/user-attachments/assets/cf672766-b3d7-48bf-ae52-05d48d443b76)

**Comment by tepene** [comment]
> > As shown in [#6 (comment)](https://github.com/ipspace/netlab/issues/6#issuecomment-2318174576), on the `vios_l2-adventerprisek9-m` image you can't configure `vrf forwarding` on the Gi0/0 interface.
> 
> ![vrf2](https://private-user-images.githubusercontent.com/2435356/363411643-cf672766-b3d7-48bf-ae52-05d48d443b76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDU3MDAsIm5iZiI6MTcyNTEwNTQwMCwicGF0aCI6Ii8yNDM1MzU2LzM2MzQxMTY0My1jZjY3Mjc2Ni1iM2Q3LTQ4YmYtYWU1Mi0wNWQ0OGQ0NDNiNzYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzFUMTE1NjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU4ZWQ3ZWU2NjdkNDk3ODg5YTA0N2EyMGQ1ZTVlMGM5MDZlZWY2MTQ1NGI0ZTgzZTk5ZGJjMDg0YTZmYjMzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JFC1px8iTHLHBw6JJ9GLoiaEvzjJKHqv_p3sTZN4RbI)

oh, sorry, forgot the `no switchport` command....my fault...

**Comment by DanPartelly** [comment]
its Ok to get the L2 images running, but tbh, L2 iosv needs proper integration. It needs a unique image type, proper VM template, and some changes to IPAM to make it work without hassle.

**Comment by DanPartelly** [comment]
Before correctness, you'll need to understand the devices themselves  to find a suitable abstraction. I do not know. Not sure its worth it.  Some IPAM changes might make the config for L2+L3 less verbose using heuristics.  But consider, l2 labs are easy. 1 topology can cover almost any lab scenario up to highest levels of qualification (assuming the images support all the crap) .  Basic support for l2 would be very cool, but also worth pondering to how much is enough and can be easily done multi vendor. 

Again, I do not know. Maybe Ivan can chime in and shed some light on what he thinks it can realistically  done relatively fast and worths the effort.

**Comment by ipspace** [comment]
Thanks a million for getting so far. I got IOSvL2 up and running (the "no switchport" bit really helped), right now I'm fixing quirks like "gee, I don't like IPv6 addresses in **ip host** command".

I'll run the integration tests and then tweak the feature flags if I find any other reduced functionality (compared to IOSv)

**Comment by DanPartelly** [comment]
> Thanks a million for getting so far. I got IOSvL2 up and running (the "no switchport" bit really helped), right now I'm >fixing quirks like "gee, I don't like IPv6 addresses in **ip host** command".

A command to enable ip routing globally on a  L2 device in the Generic Routing Configuration module would be useful if it is easy to add.

**Comment by ipspace** [comment]
> A command to enable ip routing globally on a L2 device in the Generic Routing Configuration module would be useful if it is easy to add. All those images are multilayer.

The "ip routing" or "ipv6 routing" or "ipv6 unicast-routing" command (if needed) should be configured in the initial configuration template based on the address families used on the device. On which device is this command missing? The default for IOSvL2 is "ip routing"

**Comment by DanPartelly** [comment]
My bad, you are right. It is enable by default on this image.  And yes, it make sense to use initial config if needed. 

> The "ip routing" or "ipv6 routing" or "ipv6 unicast-routing" command (if needed) should be configured in the initial configuration template based on the address families used on the device. On which device is this command missing? The default for IOSvL2 is "ip routing"

**Comment by ipspace** [comment]
IOSvL2 implementation added in #1302 -- please open new issues if I messed it up.

You can run netlab from a local Git repository if you want to check it out https://netlab.tools/install/clone/
