### ISSUE TITLE
Introduce a new unmanaged category

### ISSUE THREAD

**Issue by ryanmerolle** [ipspace/netlab#600]
Some devices like linux vms or containers, you may want to minimally manage if at all.

A category to skip management of said devices using ansible would be ideal.

However, it’s still probably useful to define the host in the ansible inventory, but create groups for managed and unmanaged.  All playbooks could then be updated to only apply to  hosts in the managed group.

Relates to #597

**Comment by ipspace** [comment]
We could easily solve this with a group with special name that would be excluded from Ansible plays. For example, if the group would be called **leave_me_alone**, we'd use **hosts: all:!leave_me_alone** in all Ansible plays.

Now: what would a good group name be? **unmanaged** could be one option, but we also have **unmanaged** flag (see #585) and I would have to use the same name for two different concepts in different places.

Any suggestions?

**Comment by ipspace** [comment]
We should not touch 99% of the use cases, so nothing special for things that should work as usual. We need something for the exceptions.

**unprovisioned** seems to be a word ;)

**Comment by ryanmerolle** [comment]
Ha not sure why I missed that.

**Comment by ipspace** [comment]
Just FYI: not provisioning Linux containers also means that those containers won't have static routes to the rest of the network (and the default route points to the host). They would still be able to access other containers over the management network (or not, depending on how _containerlab_ sets up Docker bridges) if that's good enough for your needs.

Also FYI if you go for management network access: many devices have the management interface in a management VRF.

**Comment by ryanmerolle** [comment]
That totally makes sense to me.  I’m playing with a version of the gnmic example topology and it all works over management just fine.

**Comment by jbemmel** [comment]
“untouchables” or “do_not_touch” group

**Comment by ipspace** [comment]
Implemented in 1a9f4db9b066f9b259c5657d74d02b63996aebb8
