### ISSUE TITLE
Netlab release 1.4.0

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#622]
I plan to push out 1.4.0 during this week (or next weekend). There's a PR under review that needs to get in, and another one implementing sanity checks for EVPN asymmetric IRB (waiting for the pending PR to be merged because they modify the same files).

Is there anything else you'd like to see in 1.4.0?

@ssasso: Now that netlab supports EVPN asymmetric IRB, you might want to run the `tests/integration/evpn/vxlan-asymmetric-irb.yml` test case on OS10 and VyOS (it should work out of the box once you add the feature flag) and update the documentation accordingly.

**Comment by ssasso** [comment]
> @ssasso: Now that netlab supports EVPN asymmetric IRB, you might want to run the `tests/integration/evpn/vxlan-asymmetric-irb.yml` test case on OS10 and VyOS (it should work out of the box once you add the feature flag) and update the documentation accordingly.

I will be able to do it by the end of the week.

**Comment by ipspace** [comment]
> > @ssasso: Now that netlab supports EVPN asymmetric IRB, you might want to run the `tests/integration/evpn/vxlan-asymmetric-irb.yml` test case on OS10 and VyOS (it should work out of the box once you add the feature flag) and update the documentation accordingly.
> 
> I will be able to do it by the end of the week.

That's perfect timing -- I should have both PRs merged into dev by then.

**Comment by ssasso** [comment]
Quick initial note:
Due to a probable bug on Dell OS10, I had to change the testing topology to remove *ospf* from the VRF itself:
```
vrfs:
  tenant:
    ospf: false
```
This will require more investigation on my side, but it's a "wider" bug, not related to the symmetric/asymmetric IRB but related to OSPF on a VXLAN virtual network interface.

**Comment by ipspace** [comment]
> Quick initial note: Due to a probable bug on Dell OS10, I had to change the testing topology to remove _ospf_ from the VRF itself:

Yeah, I did the same in the new version of the integration test case.

**Comment by jbemmel** [comment]
I thought https://github.com/ipspace/netlab/blob/dev/netsim/modules/evpn.py#L303 would take care of that?

(always wondered why IS-IS didn't receive the same courtesy?)

**Comment by ipspace** [comment]
> Isn't that a bug in https://github.com/ipspace/netlab/blob/dev/netsim/modules/evpn.py#L303? i.e. should also apply to the asymmetric case

No, I left it there for a reason ;) Think of asymmetric IRB as VRF Lite -- next hop should be within an EVPN VLAN segment as there is no other way to reach the next hop -- so we need routing protocols running _within_ the VRF.

> (always wondered why IS-IS didn't receive the same courtesy?)

Not many platforms implement IS-IS within a VRF, so I just decided to limit IS-IS to the global routing table ;)

**Comment by ipspace** [comment]
@ssasso: I merged everything I wanted to merge into dev, please resubmit your PR.

Thank you!

**Comment by ipspace** [comment]
Published in 2f650273d6278089a564e3d1ef9d1b4e5064e15f
