### ISSUE TITLE
Do we need to update vlan module 'fix_vlan_gateways'?

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#631]
https://github.com/ipspace/netlab/blob/5fe5010346224c3282ea874843de0671d36b2879/netsim/modules/vlan.py#L983

**Comment by ipspace** [comment]
Yeah, I remember saying "gee, I wonder what will happen on VLANs" and then it worked, and I moved on ;)

Anyway, assuming the **gateway** attribute is applied to a VLAN, it gets copied into all VLAN-enabled links (together with VLAN prefix) and so the link transformation code has something useful to work with when setting default gateway.

The code you pointed to solves the router-on-a-stick scenario with L2-only switches connecting VLAN segments.

Updated the comment ;)
