### ISSUE TITLE
Migrating to the latest vagrant-libvirt plugin

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#667]
I built a rope bridge over the Vagrant dependency hell to work around an API change in a Ruby gem **vagrant-libvirt** plugin uses. We've been using an ancient version of that plugin as some of the newer versions failed to work. It looks like now's the time to update our expectations ;)

Before changing the installation process to use the new plugin we have to test whether it works with all supported devices, but we won't be able to do that until the **vagrant-plugin** release 0.11.2 is out (due to https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1688). At that time I'll publish the upgrade instructions and the recommended testing process.

**Comment by ipspace** [comment]
Vagrant happily installs vagrant-plugin version 0.11.2 and it works with IOSv, EOS, Cumulus.

Trying to run multiple Nexus OS instances on my test box still results in occasional "ssh timeouts" that seem to be hard-coded at two seconds, otherwise it works.

vSRX also works (with increased CPU quota and command timeout)

@ssasso Could you please test your platforms with the new plugin before we start using it in the installation script?

**Comment by ssasso** [comment]
I'm happily using 0.11.2:
```
root@hippo:~# vagrant plugin list
vagrant-guests-photon (1.0.5, global)
  - Version Constraint: > 0
vagrant-libvirt (0.11.2, global)
vagrant-mutate (1.2.0, global)
  - Version Constraint: > 0
```

with VyOS, Mikrotik ROS and Dell OS10 (and EOS as well).

**Comment by ipspace** [comment]
Thank you!
