### ISSUE TITLE
netlab-generated YAML must be in YAML 1.1 format (quoted RD values)

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#677]
Summarizing #669 and #676:

* python-box could use ruamel.yaml if it's installed (not sure how exactly that works, I got mixed results)
* ruamel.yaml generates YAML 1.2 which does not quote sexagesimal numbers
* Ansible uses PyYAML which supports YAML 1.1
* RDs in ruamel-generated inventory are thus interpreted as integers resulting in incorrect device configurations

We have two options:

* Make sure ruamel.yaml is not used by python-box (PyYAML should be installed anyway as it's an Ansible dependency). Not sure how to do that yet
* Tell ruamel.yaml to use YAML 1.1 with **ruamel_attrs** parameter to box.to_yaml. Unfortunately this requires box 6.0 or above, and we need to do thorough testing before changing dependencies to box 6.0+

I guess we won't solve this conundrum in the next 20 minutes, more tomorrow...

**Comment by ipspace** [comment]
Update:

* We cannot force python-box 5.4.1 to use PyYAML without uninstalling ruamel.yaml.
* python-box 6.1.0 seems to work. All the tests have passed, so maybe we can go for it.
* Using ruamel-yaml breaks all the tests as the keys in the YAML output are not sorted. Have to figure out how to change that :(

**Comment by ipspace** [comment]
Update#2:

* Using ruamel_attrs @jbemmel found in #676 (but with YAML version pinned to 1.1) generates correct YAML file with quoted RDs.

Plan:

* Figure out how to sort keys in YAML output with ruamel
* Once we have the final set of ruamel_attrs, add the to every call of `to_yaml()`
* Update the requirements.txt to use box 6.1.0

Have I missed anything @jbemmel?

**Comment by jbemmel** [comment]
Sort: see https://stackoverflow.com/questions/40226610/ruamel-yaml-equivalent-of-sort-keys

**Comment by ipspace** [comment]
This thing is getting crazier:

* The "sort keys" workaround for ruamel.yaml is pure bollocks. I figured out how to make it work (recreate the dictionary with sorted keys), but it still sucks big time.
* While python-box prefers ruamel.yaml over pyyaml, the ruamel dependency is an optional one -- ruamel is not installed if you install python-box without additional options, so we're perfectly fine not using ruamel.

On a positive side: everything seems to work well with Box 6.1.0, so we can change the requirements to use it.

Interesting fact: Ansible is definitely **not** using ruamel. I did a search for "import ruamel" in Ansible core and there were zero hits.

Anyway, the only time we're experiencing the challenges in #669 is if someone else installed ruamel while pyyaml is also installed. We could turn this into a warning (repeated in the VRF, MPLS and EVPN modules), or we could create crazy workaround for missing/different ruamel functionality.

Any preferences @jbemmel @ssasso @petercrocker?

**Comment by jbemmel** [comment]
Netlab does not explicitly import ruamel, but it still gets used when installed…

**Comment by ipspace** [comment]
> Netlab does not explicitly import ruamel, but it still gets used when installed…

Yeah, that's pretty much a direct consequence of what I wrote above ;) Any preferences how we should handle that? Try to survive the complexity of dealing with ruamel or document it doesn't work?

**Comment by jbemmel** [comment]
I would say upgrade to Box 6.1.0, add the 'version' parameter to force YAML 1.1 when ruamel is installed, and document the caveat. I'm not concerned about the automated tests "failing" because of the ordering of keys - if anything, the tests could be fixed to sort the output themselves before comparing and declaring "failed"

**Comment by ipspace** [comment]
> I would say upgrade to Box 6.1.0, add the 'version' parameter to force YAML 1.1 when ruamel is installed, and document the caveat.

Sounds like a perfect plan. Also, we probably have enough tests that we'll quickly detect if a future version of Box starts acting weird (on the first **git push**) so we don't have to pin the version.

Thank you -- it's really nice having someone with a different perspective when I'm too deep in the woods.

> I'm not concerned about the automated tests "failing" because of the ordering of keys - if anything, the tests could be fixed to sort the output themselves before comparing and declaring "failed"

Also correct. As we control the test environment, we can make sure it uses PyYAML.

**Comment by ipspace** [comment]
Fixed in #678
