### ISSUE TITLE
Switching to 'busybox' Linux container

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#704]
After #703 we can use any container image as the Linux container.

Right now, the default image is `python:3.9-alpine` because the deployment process used Ansible `template` module which required Python in the container. With the new deployment process we could use the `busybox:latest` container.

Any objections? Is there a better container to use as the default?

/cc @ssasso @jbemmel @petercrocker

**Comment by sysoleg** [comment]
What I really like with the current default image is the ability to quickly install some package using alpine's ``apk``. For example, ``tcpdump``. alpine:latest is 7.05MB while busybox:latest is 4.86MB. Not a huge difference.

**Comment by ssasso** [comment]
> What I really like with the current default image is the ability to quickly install some package using alpine's `apk`. For example, `tcpdump`. alpine:latest is 7.05MB while busybox:latest is 4.86MB. Not a huge difference.

+1 for `alpine:latest`

**Comment by ipspace** [comment]
Got the message loud and clear. Closing... ;)
