### ISSUE TITLE
Running multiple labs on the same Linux server

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#722]
When using _netlab_ to build automated test environments one might have to run multiple labs on the same Linux server. _netlab_ cannot do that (reliably) at the moment because it uses hardcoded management IP address ranges, tunnel endpoints, and libvirt/Linux bridge names.

One way to give the users who want to build an automated multi-lab system the necessary tools would be to introduce **lab_id**, a new system default parameter that would influence a number of other things (see below). The **lab_id** and the lab name (which also influences VM/container names and bridge/network names) would then be set via the CLI parameters. **lab_id** would become a mandatory parameter, and when it would be set to None in user defaults, it would be impossible to start the lab without specifying **lab_id** as a CLI parameter.

This is a (probably partial) list of parameters that have to rely on **lab_id** to generate unique values for each lab:

* Management IPv4/IPv6 prefix
* Lab name if you want to run multiple copies of the same lab
* libvirt and clab management network name and underlying Linux bridge name
* libvirt network names (Linux bridge name is auto-generated from libvirt network ID)
* Tunnel endpoints for P2P links implemented with UDP tunnels
* Linux bridges used to implement stub or multi-access networks in clab

Notes:
* VM and container names are already generated from lab name
* libvirt in-lab network names and clab Linux bridges are also generated from lab name -- we just have to make sure we don't exceed 16 character naming limit

Anything else I've missed @petercrocker?

**Comment by petercrocker** [comment]
I discussed this with our team that wants to use and help code this. You've captured all the objects that I can think of that would be affected. Round 1 of our usage would just to be specify **lab_id** in the `topology.yml` file. We can build on it from there after we've got some usage.

**Comment by jbemmel** [comment]
@petercrocker it doesn't make sense to me to have lab_id in the topology file - it is a property of an instance you're launching.

I would suggest to start with lab_id as an optional CLI parameter (default "1" if not specified)

**Comment by petercrocker** [comment]
We have two teams/workflows:

- Static labs. Up all the time. My dev team wants to switch from EVE-NG to labs-as-code, so it's easier to maintain. Here lab_id in topology file works well for them.
- Dynamic labs. We do some testing, then destroy the lab. Labs are up for days, not much more. Here we're fine with lab_id in topology for round 1, but also we're already thinking of how to extend it:
  - lab_id as cli option on `netlab up`
  - lab_id in a dotfile (each user though can only have one lab)
  - dynamically generated lab_id. @ipspace had a good idea how to implement. If `lab_id == X` then call a plugin. The plugin's job is to maintain state, and return the next unused lab_id. It could be as simple as a flatfile db, and some commands to verify `virsh` state for example

But I want to start small and easy, and learn from usage and experience. We thought lab_id in topology would be simplest for round 1.

**Comment by ipspace** [comment]
@petercrocker The code is (mostly) ready in ml-722 branch (in the "it works for me" state). Have to write the documentation, then I'll open a PR and send it over for review (= test in real life)

**Comment by ipspace** [comment]
@petercrocker Created a PR and assigned you as a reviewer. It would be great if you could pull down that branch and do a few tests running multiple labs on the same system.

**Comment by petercrocker** [comment]
This is fantastic @ipspace thanks! I was assuming we'd be doing the work on this one. I'll spin this up on our server and report back, as well as review the PR.

**Comment by ipspace** [comment]
Implemented in #733
