### ISSUE TITLE
Use Ansible as the templating engine when generating container files

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#772]
_netlab_ can generate container configuration files using templates specified in `clab.config_templates` during the **netlab up** process. Those templates are processed with the vanilla Jinja2 engine which means they cannot use filters available in Ansible playbooks like **ipaddr**.

Add `clab.template_engine` parameter that can have two values: `jinja2` or `ansible`. When the parameter is set to `ansible` use **ansible** command to process the template:

```
ansible -m template -e ansible_connection=local _host_ -a 'src=_template_path_ dest=./_target_'
```

**Comment by jbemmel** [comment]
If Ansible is a superset, wouldn’t it be simpler to just default to that? When would a user need vanilla Jinja2?

**Comment by ipspace** [comment]
I'm not really comfortable with making Ansible a mandatory prerequisite for core netlab functionality. Also, using Ansible template module is awfully slow when compared to a simple call to Jinja2 template.

**Comment by jbemmel** [comment]
Perhaps we could load Ansible's Jinja2 filter extensions into the default Jinja2 engine, when available?

See e.g. https://pypi.org/project/jinja2-ansible-filters/
```
from jinja2 import Environment
...
  env = Environment(extensions=['jinja2_ansible_filters.AnsibleCoreFiltersExtension'])
...
```

preceded by an import test if needed (not sure how Jinja2 behaves when it cannot load the declared extensions)

**Comment by ipspace** [comment]
Great find, but unfortunately those filters don't include **ipaddr** (the thing I was really looking for). Also, the filter names are not the same as in Ansible (they are prefixed with `ans_` to avoid overlaps with builtin Jinja2 filters), so the user would have to keep track of which filter to use based on where the template is used (device configuration versus container configuration file).

Anyway, following your suggestion I tried to find an **netaddr** wrapper and of course there is one, but yet again using filter names that are different from what Ansible uses.

https://pypi.org/project/j2ipaddr/

**Comment by jbemmel** [comment]
This works (in common.py):
```
try:
    from ansible_collections.ansible.utils.plugins.plugin_utils.base.ipaddr_utils import ipaddr
    ENV.filters["ipaddr"] = ipaddr
  except:
    if debug_active('template'):
      print( "Unable to load Ansible ipaddr_utils, 'ipaddr' filter not available" )
```

**Comment by ipspace** [comment]
Replaced by #781. Will close when that one gets merged.
