### ISSUE TITLE
Virtual (tunnel) interfaces/links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#780]
@abaretta would like to build a topology with numbered IPsec tunnel interfaces and would like netlab to manage the IP subnet/addresses of those interfaces.

We're almost there with per-interface **ifname** used by the **external** provider, but we need to have a mechanism to remove the virtual link from the list of links (similar to the **loopback** links) otherwise _netlab_ thinks it has to create a Linux bridge for it, and connect VM/container interfaces to that bridge (which _might_ work if the tunnel link happens to be the last link in topology, but it's still a mess).

So, we need something that would behave almost like **loopback** links but without the *one node per link* check:

* Link `type: virtual` would be used to create virtual links
* Nodes connected to virtual links MUST have `ifname` attribute (or whatever it is)

Behind the scenes:

* _netlab_ would manage link subnets and node IP addresses
* virtual interfaces will be added to the node data structure
* like `loopback` links, the `virtual` links will be removed from the list of links before the end of transformation

Any better ideas or suggestions? /cc @jbemmel

**Comment by jbemmel** [comment]
Link ```type: tunnel``` perhaps? Is it always between exactly 2 nodes?

**Comment by abaretta** [comment]
I would think so... For point-to-multipoint tunnels one node can terminate several tunnels on the same tunnel interface though, no idea if that is an issue for the data model or not?

**Comment by ipspace** [comment]
- Data model has no problems with numerous nodes attached to the same link, it's just that sometimes (in case of P2P or loopback links) we test whether the number of nodes is what we expect.
- Tunnel can have one node (MPLS-TE, just the head-end), two nodes (the usual GRE tunnels), or more nodes (mGRE/DMVPN/...)
- Assuming we configure IP on physical/VLAN interfaces, then anything we want to run over that between nodes must be a tunnel, so `type: tunnel` might be less generic than `type: virtual` but more applicable. Let's go with that.

Will code this in the next few days (hint: it seems the rainy season has started 🥴).

**Comment by ipspace** [comment]
Implemented in da5103ac7034b446c8175c358a9a9e30a724c214
