### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#796]
https://github.com/ipspace/netlab/blob/c7719d362b07bc03877ffefd70a9d3a0ebc6a8b8/docs/release/1.5.md?plain=1#L17

Wondering if there is a lint tool that could catch these?

**Comment by ipspace** [comment]
That works when built with sphinx:

https://netsim-tools.readthedocs.io/en/latest/release/1.5.html#release-1-5-2

Install requirements from `requirements-dev.txt` and run `make html` in docs directory. Sphinx reports all broken links, so there's no need for an additional tool.
