### ISSUE TITLE
Latest release requires python-box 7.0.x

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#797]
For example: https://github.com/jbemmel/netsim-examples/blob/master/NextLevel/topology.yml#L34

```
bgp.as_list:
  65000:
    members: [ s1, s2 ]
  65100:
    members: [ pe1,pe2 ]
```

With the latest release, this is no longer supported unless rewritten to:
```
bgp:
  as_list:
    <etc>
```

**Comment by ipspace** [comment]
You have to upgrade python-box to 7.0.x. That's done automatically for people installing with **pip3** (the latest release changed `requirements.txt`) but I cannot enforce that when using GitHub repo. We could add a `box` version check somewhere?

**Comment by jbemmel** [comment]
Something like:
```
>>> import pkg_resources

>>> pkg_resources.get_distribution("python-box").version

'7.0.1'
```

**Comment by ipspace** [comment]
import box; box.__version__ is even simple ;)

The real question is: should we care? This impacts only the few people who pull down the repo.
