### ISSUE TITLE
Juniper vPTX randomically not taking DHCP address on managment interface

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#821]
For unknown reasons, in some unknown circumstances (i.e., 1 VM every 3), the Junos vPTX image is failing to receive a DHCP address on the management interface.

Resetting the interface, the address is bound.

Under investigation.

```
vagrant@vptx> show dhcp client binding

1 clients, (0 init, 0 bound, 0 expired, 1 failed, 0 stop)
IP address        Hardware address   Expires     State      Interface
0.0.0.0           08:4f:a9:00:00:01  0           FAIL       re0:mgmt-0

vagrant@vptx# deactivate interfaces re0:mgmt-0

[edit]
vagrant@vptx# commit
commit complete

[edit]
vagrant@vptx# activate interfaces re0:mgmt-0

[edit]
vagrant@vptx# commit and-quit
```

This happens also on "plain KVM" VMs.

**Comment by ipspace** [comment]
Doesn't it get the IP address on the management interface during **vagrant up**? I through Vagrant won't move on until a device is reachable (via SSH) on its management interface

**Comment by ssasso** [comment]
> Doesn't it get the IP address on the management interface during **vagrant up**? I through Vagrant won't move on until a device is reachable (via SSH) on its management interface

exactly, that's why it's a problem for "us".

(the interface reset above was done via serial)

**Comment by ipspace** [comment]
* Did you use **netlab up** or **vagrant up** to start it?
* What do the `dnsmasq` bindings say? Is Vagrant claiming the device got IP address but is not reachable via SSH or is it stuck before that?
* Any chance of running a custom script that would reset the interface if needed? I had to do some similarly-crazy stuff for Cumulus containers (IIRC also due to weird `dnsmasq` behavior)

**Comment by ssasso** [comment]
> * Did you use **netlab up** or **vagrant up** to start it?

tried with both, and related debug flags

> * What do the `dnsmasq` bindings say? Is Vagrant claiming the device got IP address but is not reachable via SSH or is it stuck before that?

Currently troubleshooting with a mix of tcpdump on the bridge (to see if there are low level differences on the packets) and dnsmasq syslog, but the "problem" happens randomically, so it's hard to troubleshoot.

**Comment by ipspace** [comment]
You could probably do a capture of the VM NIC interface, but I'm guessing you won't find anything new (no idea whether the VM interface reset triggers an event on the host). Looks like a Juniper problem to me... unless there's something in the MAC address that upsets them?

Any chance of turning on logging on Junos to see what it thinks is going on?

**Comment by ssasso** [comment]
Looks like a Junos problem to me as well.
Working on a workaround script.

**Comment by ipspace** [comment]
vPTX DHCP client fails consistently on (my) Ubuntu 22.04. DHCP server responds to the request, offers the correct IP address, the vPTX client requests the address, gets the acknowledgement, and the rejects the IP address, throwing DHCP into a permanent loop as the DHCP server tries to offer different dynamic addresses that are all rejected.

Will retry with a freshly-built Ubuntu VM.

**Comment by ssasso** [comment]
Hi @ipspace , this is what we tried to verify with Juniper team, but we never got a feedback from them (or, at least, I never got it).
Is there any chance you can try to contact them again on this?

(site note: did you try the workaround? is that working? maybe we can find a way to launch it from vagrant?)

**Comment by ipspace** [comment]
> Hi @ipspace , this is what we tried to verify with Juniper team, but we never got a feedback from them

Yeah, they sort-of gave up. Also, the behavior I'm observing is completely different from what you've seen. I'm rebuilding a fresh Ubuntu 22.04 VM right now to retest the whole thing.

**Comment by ipspace** [comment]
Looks like the latest vPTX release works, and _netlab_ doesn't support older releases anyway, so I'm closing this one.
