### ISSUE TITLE
[docs] all caveats links are broken from the platforms page

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#826]
From here: https://netlab.tools/platforms/ - all the caveats links are broken

(sending to https://netlab.tools/platforms/caveats.html#xxxx instead of https://netlab.tools/caveats/)

**Comment by ipspace** [comment]
New version of myst_parser handles tables and links within tables correctly ;) Fixing documentation...

**Comment by ipspace** [comment]
Fixed in 527cebda07fb8cc73f004ad8b0029a182c4e906d
