### ISSUE TITLE
Netlab does not report an error when it cannot perform libvirt network changes

### ISSUE THREAD

**Issue by reallyseaneverson** [ipspace/netlab#854]
### Describe the bug

The ip addressing expected by netlab for the libvirt management network is not present.  Netlab is expecting the mgmt ips to start at .100.  I am seeing the first host get an ip of .250

### To Reproduce

netlab up or netlab initial will recreate the error on my system.  I used netlab test libvirt to generate the test topology.  I see the issue with the test topology and any that I create.

### Output

Here is output from a netlab initial run for the built in test topology:
ASK [copy cumulus config to /tmp/config.sh] *********************************************************************************************************
fatal: [s1]: UNREACHABLE! => changed=false
  msg: '[Errno None] Unable to connect to port 22 on 192.168.121.101'
  unreachable: true
fatal: [s3]: UNREACHABLE! => changed=false
  msg: '[Errno None] Unable to connect to port 22 on 192.168.121.103'
  unreachable: true
fatal: [s2]: UNREACHABLE! => changed=false
  msg: '[Errno None] Unable to connect to port 22 on 192.168.121.102'
  unreachable: true
PLAY RECAP *******************************************************************************************************************************************
s1                         : ok=5    changed=0    unreachable=1    failed=0    skipped=2    rescued=0    ignored=0
s2                         : ok=5    changed=0    unreachable=1    failed=0    skipped=2    rescued=0    ignored=0
s3                         : ok=5    changed=0    unreachable=1    failed=0    skipped=2    rescued=0    ignored=0
Fatal error in netlab: Executing Ansible playbook /usr/local/lib/python3.10/dist-packages/netsim/ansible/initial-config.ansible failed:
  Command '['ansible-playbook', '/usr/local/lib/python3.10/dist-packages/netsim/ansible/initial-config.ansible']' returned non-zero exit status 4.

vagrant ssh-config s1:
Host s1
  HostName 192.168.121.250
  User vagrant
  Port 22
  ...

vagrant ssh-config s2:
Host s2
  HostName 192.168.121.251
  User vagrant
  Port 22
  ...

vagrant ssh-config s3:
Host s3
  HostName 192.168.121.252
  User vagrant
  Port 22
  ...

I appear to have a mismatch between the assigned by libvirt ip addresses and the expected by netlab addresses.

### Version

netlab version 1.5.4-post1

### Additional context

This is on an ubuntu 22.04.2LTS host with libvirt version 8.0.0-1ubuntu7.6.

**Comment by ipspace** [comment]
The root cause is the (lack of) static DHCP mapping in the vagrant-libvirt network. Please

* run `virsh net-list --all` command before you run `netlab up` to verify that network is not there
* run `netlab up --no-config` to start the VMs but not the provisioning script
* execute `virsh net-dumpxml vagrant-libvirt`-- you should see something along these lines:

```
<network connections='2'>
  <name>vagrant-libvirt</name>
  <uuid>3c634c35-63fa-4ca0-a1c8-4a0335aa9599</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='libvirt-mgmt' stp='on' delay='0'/>
  <mac address='52:54:00:d8:3f:0d'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.2' end='192.168.121.99'/>
      <host mac='08:4F:A9:00:00:01' ip='192.168.121.101'/>
      <host mac='08:4F:A9:00:00:02' ip='192.168.121.102'/>
      <host mac='08:4F:A9:00:00:03' ip='192.168.121.103'/>
      <host mac='08:4F:A9:00:00:04' ip='192.168.121.104'/>
      <host mac='08:4F:A9:00:00:05' ip='192.168.121.105'/>
      <host mac='08:4F:A9:00:00:06' ip='192.168.121.106'/>
      <host mac='08:4F:A9:00:00:07' ip='192.168.121.107'/>
      <host mac='08:4F:A9:00:00:08' ip='192.168.121.108'/>
      <host mac='08:4F:A9:00:00:09' ip='192.168.121.109'/>
      <host mac='08:4F:A9:00:00:0A' ip='192.168.121.110'/>
      <host mac='08:4F:A9:00:00:0B' ip='192.168.121.111'/>
      <host mac='08:4F:A9:00:00:0C' ip='192.168.121.112'/>
      <host mac='08:4F:A9:00:00:0D' ip='192.168.121.113'/>
      <host mac='08:4F:A9:00:00:0E' ip='192.168.121.114'/>
      <host mac='08:4F:A9:00:00:0F' ip='192.168.121.115'/>
      <host mac='08:4F:A9:00:00:10' ip='192.168.121.116'/>
...
```

If there are no DHCP mappings on your `vagrant-libvirt` network then libvirt messes up network creation, if the mappings are there but are not honored then it's another dnsmasq quirk (and we might have to install specific version of dnsmasq in the installation script).

**Comment by ipspace** [comment]
FWIW, I created a brand-new Ubuntu 22.04 VM (from `generic/ubuntu2204` Vagrant box), installed software on it using **netlab install** commands and it works as expected. You must have a somewhat funky setup.

**Comment by reallyseaneverson** [comment]
While running through the above commands I noticed that the vagrant-libvirt network was listed as inactive before and after the netlab up --no-config command you provided.

Manually starting the network in virsh gave this error:

`~/work/netlabs$ virsh net-start vagrant-libvirt
error: Failed to start network vagrant-libvirt
error: error creating bridge interface libvirt-mgmt: Operation not permitted`

Validating my permissions and installation led me to this superuser post: https://serverfault.com/questions/803283/how-do-i-list-virsh-networks-without-sudo.

my issue appears to be that I did not have a $LIBVIRT_DEFAULT_URI env var that pointed to the proper qemu URI.  After running:

`export LIBVIRT_DEFAULT_URI=qemu:///system `

All commands work as expected and netlab test libvirt is able to connect to the machines during the netlab initial step.

I believe that setting this uri in my env has resolved my issue.

Appreciate the prompt response!

**Comment by ipspace** [comment]
So nice to hear you solved it ;) We usually solve the permission problem by adding the netlab user to the libvirt group in the `netlab install libvirt` installation script, but it would definitely be nice to report an error. Will try to figure it out.

**Comment by reallyseaneverson** [comment]
My machine may be nonstandard as I have been doing other dev work on it.  May not be a stock ubuntu env at this point.

You noted that the install should add a netlab use to the libvirt group.  I don't see a netlab user on my machine at moment.  I added my own user to the libvirt group.  Should I have a netlab user as part of the install process?  

I followed the steps for Ubuntu Server from the website for my initial installation.

The lab examples I downloaded are now working as expected so my install appears to be functional.

**Comment by ipspace** [comment]
> You noted that the install should add a netlab user to the libvirt group.

My bad. I should have written "**netlab install libvirt** adds the current user to the **libvirt** group" -- will add a note to https://netlab.tools/labs/libvirt/

> I don't see a netlab user on my machine at moment. I added my own user to the libvirt group. Should I have a netlab user as part of the install process?

No, I apologize for the confusion.

> The lab examples I downloaded are now working as expected so my install appears to be functional.

Perfect. Thanks for the confirmation!

**Comment by ipspace** [comment]
Failed to reproduce the error (so far). If I remove `vagrant` user from `libvirt` group then `virsh net-list` fails miserably and the provider check (the first step in **netlab up** process) fails with an explicit `you have to be in libvirt group` error message.

**Comment by ipspace** [comment]
Managed to reproduce the problem, had to set $LIBVIRT_DEFAULT_URI manually to `qemu:///session` 🤷‍♂️

**netlab up** now sets the LIBVIRT_DEFAULT_URI environment variable to `qemu:///system` before executing `virsh` commands to ensure it's creating the networks visible by **vagrant-libvirti** plugin.
