### ISSUE TITLE
Connect mgmt interfaces to existing network/bridge

### ISSUE THREAD

**Issue by achurak** [ipspace/netlab#855]
Hello,

Is there any way to connect the mgmt interfaces to the existing network/bridge? I'd like these VMs to be accessible from the outside world and to be able to spin up additional VMs manually and attach them to the same management space.
I found the `_network` and `_bridge` parameters in the documentation however it appears that they only allow to define custom bridge/network names and even if they already exist netlab still tries to create them and then throws an exception:

`Error while activating network: Call to virNetworkCreate failed: error creating bridge interface br-netlab: File exists.`

And on top of that it still deletes the virsh network.

I also see that it's possible to connect other links to the existing bridges and prevent the netlab from trying to delete them with the `permanent` option set to `True`, so is there a similar option for the management network that I've just missed?

Thanks!

**Comment by ipspace** [comment]
While you can set the name of the management network (https://netlab.tools/labs/libvirt/#libvirt-management-network) you cannot make it persistent across lab starts. Thank you, will add an option.

**Comment by ipspace** [comment]
The fix is also available on pypi as version 1.5.5-dev1, install with `pip3 install --upgrade --pre networklab`
