### ISSUE TITLE
FRR templates produce incompatible mix between VPN address family related config and VRF leaking

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#861]
https://github.com/ipspace/netlab/blob/9030aa0c2f99c76c2d39c4340387bef438257d54/netsim/ansible/templates/vrf/frr.bgp.j2#L19

Looking at https://docs.frrouting.org/en/latest/bgp.html#general-configuration, my understanding is that these commands are related to the VPN AF, and hence should be conditional on mpls.vpn being defined

What happens
```
      router bgp 65000 vrf internet
       no bgp ebgp-requires-policy
       no bgp default ipv4-unicast
       address-family ipv4 unicast
        label vpn export auto
        export vpn
        import vpn
        rd vpn export 65000:1
        rt vpn import 65000:1
        rt vpn import 65000:2
        rt vpn import 65000:3
        rt vpn export 65000:1
        redistribute connected
        import vrf customer1
        import vrf customer2
        network 10.2.0.3/32
       exit-address-family
      !
      !
      CONFIG
      vtysh -f /tmp/vrf_config
      exit $?

TASK [run /tmp/config.sh to deploy vrf config from /home/jeroen/srlinux/netlab/netsim/ansible/tasks/../templates/vrf/frr.j2] **************************************************************************************
task path: /home/jeroen/srlinux/netlab/netsim/ansible/tasks/deploy-config/frr.yml:7
redirecting (type: connection) ansible.builtin.docker to community.docker.docker
redirecting (type: connection) ansible.builtin.docker to community.docker.docker
fatal: [frr-bgp-s2]: FAILED! => changed=true 
  cmd:
  - bash
  - /tmp/config.sh
  delta: '0:00:00.070518'
  end: '2023-08-17 15:16:17.624412'
  msg: non-zero return code
  rc: 13
  start: '2023-08-17 15:16:17.553894'
  stderr: |-
    line 21: Failure to communicate[13] to bgpd, line:   import vrf internet
  
    line 37: Failure to communicate[13] to bgpd, line:   import vrf internet
  
    line 54: Failure to communicate[13] to bgpd, line:   import vrf customer1
  
    line 55: Failure to communicate[13] to bgpd, line:   import vrf customer2
  stderr_lines: <omitted>
  stdout: |-
    % error: Please unconfigure vpn to vrf commands before using import vrf commands
    % error: Please unconfigure vpn to vrf commands before using import vrf commands
    % error: Please unconfigure vpn to vrf commands before using import vrf commands
    % error: Please unconfigure vpn to vrf commands before using import vrf commands
  stdout_lines: <omitted>
```

(can extract a lab to reproduce, just wanted to start an initial discussion if this makes sense)

**Comment by ipspace** [comment]
It's clearly a bug and it needs to be fixed. It's great that you found it (and it might be in the Cumulus code as well).

I don't think it has anything to do with MPLS/VPN (_blame_ claims the problematic bit of the code was added way before Oleg implemented MPLS/VPN), and FRR documentation claims "A shortcut syntax is also available for specifying leaking from one VRF to another VRF using the default instance’s VPN RIB as the intermediary." so it uses the VPN RIB anyway. It probably worked at that time, so I'm guessing they tightened the controls in FRR, specifically (from their documentation)

> This shortcut syntax mode is not compatible with the explicit import vpn and export vpn statements for the two VRF’s involved. The CLI will disallow attempts to configure incompatible leaking modes.

Will figure out what needs to be done (I doubt _removing import VRF commands_ is the correct answer) and fix it, but it might take a bit.

**Comment by ipspace** [comment]
Turns out "removing import VRF commands" was the right thing to do, but by far not the only thing that needed to be fixed. Looks like you were the first one trying to do inter-VRF route leaking on FRR. Thanks again for reporting this one!
