### ISSUE TITLE
[DOC] Install: clab on Ubuntu 22+ needs modules from linux-modules-extra

### ISSUE THREAD

**Issue by robert-nix** [ipspace/netlab#872]
I ran into a little hang-up running bgplabs on a fresh Ubuntu 22 VM from DigitalOcean. I was having the Cumulus router setup hang forever within the `ifreload -a` loop in bgp/cumulus.j2. Abridged `ifreload -a -d` output:

```
# ifreload -a -d
...
Traceback (most recent call last):
  File "/usr/share/ifupdown2/addons/vrf.py", line 799, in _up_vrf_dev
    vrf_table = self._create_vrf_dev(ifaceobj, vrf_table)
  File "/usr/share/ifupdown2/addons/vrf.py", line 760, in _create_vrf_dev
    self.log_error('create failed (%s)' % str(e), ifaceobj)
  File "/usr/share/ifupdown2/ifupdownaddons/modulebase.py", line 113, in log_error
    raise Exception(str)
Exception: create failed (operation failed with 'Operation not supported' (95))
...
info: exit status 1
```

Turns out the vrf module was moved to linux-modules-extra packages in Ubuntu 22, and so what was required was a `sudo apt install linux-modules-extra-$(uname -r)`. After this everything works as expected.

This could either be documented, or potentially nicer would be adding it to the `netlab install ubuntu` script.

**Comment by ipspace** [comment]
Good catch, it should definitely go into Ubuntu installation script. Would you like to become a contributor and submit a PR or should I add it?

**Comment by ipspace** [comment]
Thank you!
