### ISSUE TITLE
BGP authentication for ibgp sessions

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#893]
https://github.com/ipspace/netlab/blob/ca4dc8ac33973e47a69da91469aa68990272a295/tests/topology/expected/ebgp.utils.yml#L158

It's called the "ebgp.utils" plugin so one could argue this is F-A-D, but... shouldn't a global 'bgp.password' apply also to ibgp sessions?

**Comment by ssasso** [comment]
ok for me, no problem!
