### ISSUE TITLE
bgp.session plugin should normalize remove_private_as attribute value to list of strings

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#927]
The documentation says `remove_private_as` can be provided as a simple Boolean, a string or a list of strings.

The plugin templates assume a list of strings

**Comment by ipspace** [comment]
... because the data transformation process transforms all of the valid input types into a list of strings ;)

See https://github.com/ipspace/netlab/blob/dev/netsim/extra/bgp.session/defaults.yml#L168
