### ISSUE TITLE
[BUG] install broken if user is root?

### ISSUE THREAD

**Issue by ssasso** [ipspace/netlab#951]
### Describe the bug

Don't know if this is happening only to me,
I tried to perform a fresh install on a new virtual machine w/ Ubuntu 22.04, but when launching the installation **directly as root**, the install scripts are "broken".

### To Reproduce

In example, looking at https://github.com/ipspace/netlab/blob/2a38f37309e4592072289c6ec019980bca587528/netsim/install/ubuntu.sh#L16 

when the user is already root, the *SUDO* var stays untouched, and this results in:
```
root@clab-playground:~# SUDO='DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a'
root@clab-playground:~# $SUDO apt-get update -y
DEBIAN_FRONTEND=noninteractive: command not found
root@clab-playground:~#
```

### Solution/Workaround

Quick & Dirty workaround is to always use *sudo*, even if you are root:
```
root@clab-playground:~# SUDO='DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a'
root@clab-playground:~# SUDO="sudo $SUDO"
root@clab-playground:~# $SUDO apt-get update -y
Get:1 https://download.docker.com/linux/ubuntu jammy InRelease [48.8 kB]
Get:2 https://apt.releases.hashicorp.com jammy InRelease [12.9 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
```

**Comment by ipspace** [comment]
This definitely needs to get fixed. I broke it when fixing stuff for Ubuntu 22.04. Will try to figure out the right decision tree -- we definitely should keep the environment variables in Ubuntu 22.04, but it would also be nice to support systems without `sudo` (that's where the original patch was coming from).

**Comment by ssasso** [comment]
Since we are in any case installing packages, may I propose as a first of the scripts step to install sudo, if not present?

So,

- If not root, and sudo not present, exit 1
- If root, and sudo not present, install sudo
- everything else

**Comment by ipspace** [comment]
That would mean we have to find package to install, which might depend on the distro version.

We could also say "if sudo is not installed, then we're not on Ubuntu 22.04, and so we don't have to worry about environment variables, set SUDO to empty string" Would that work?

**Comment by ssasso** [comment]
well, sudo is installed by default in any ubuntu version, so the check you proposed is not fully "real".

But, since on the install scripts we are considering only apt-based distributions, the sudo package is always sudo :) (i.e. https://packages.debian.org/bookworm/sudo)

**Comment by ipspace** [comment]
> well, sudo is installed by default in any ubuntu version, so the check you proposed is not fully "real".

Let's try again: if sudo is not installed, then we're definitely not on Ubuntu 22.04, so we don't have to worry about environment variables that were added to cope with 22.04. Does this make more sense?

> But, since on the install scripts we are considering only apt-based distributions, the sudo package is always sudo :) (i.e. https://packages.debian.org/bookworm/sudo)

OK, I could work with that ;)
