### ISSUE TITLE
[DOC] Please provide command for executing netlab from PowerShell command line

### ISSUE THREAD

**Issue by tomaskrajco** [ipspace/netlab#957]
### What's wrong

Please provide the command to run netlab from PowerShell command line.

**Comment by ipspace** [comment]
No idea. I don't think anyone involved with the project is running it directly on Windows.

Will write a blog post asking for contributions to documentation, maybe someone will chime in. In the meantime, it's always possible to create a Ubuntu VM on Windows and run your netlab-powered labs within that VM.

https://netlab.tools/install/ubuntu-vm/

From a slightly wider perspective: what problem are you trying to solve? Why would you like to use PowerShell?

**Comment by tomaskrajco** [comment]
I'm trying to get into ipv6

**Comment by ipspace** [comment]
> I'm trying to get into ipv6

That's commendable, but still doesn't explain the "I want to start netlab with PowerShell" part

**Comment by tomaskrajco** [comment]
We are using a lot of PowerShell in work

**Comment by ipspace** [comment]
> We are using a lot of PowerShell in work

No responses to the blog post asking for helpful hints I published a few days ago. Looks like nobody else went down the "running _netlab_ on Windows" route. It might be best if you create a Ubuntu VM as suggested and run your lab on it.

**Comment by ipspace** [comment]
Got zero suggestions, the best path still seems to be "run Ubuntu VM" which is now documented as the recommended option for Windows users
