### ISSUE TITLE
[BUG] Breaking change: vPTX no longer needs the back-to-back links

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#964]
Long story short: Juniper discovered vEth interfaces ;)

The new vPTX (`vJunosEvolved-23.2R1-S1.8-EVO.qcow2`) no longer needs the first four interfaces attached to external bridges. The box creation is not impacted, but when you use vPTX in the lab, the Vagrantfile still adds four extra interfaces to the VM and the first "usable" interface is `et-0/0/4`. Obviously, nothing works.

I can't figure out how to handle the old- and the new behavior in a graceful way. We could declare it a breaking change in release 1.7.0 and tell everyone to use the new vPTX release (that could be the best approach assuming not too many people use vPTX), or we could add a device flag that would create old- or new-style Vagrantfile, but then the question is "what should the default value of that flag be?"

Any ideas @ssasso @jbemmel?

**Comment by ipspace** [comment]
> Given the "limitations" of the previous vPTX release

BTW, DHCP works ;))

> I would declare a breaking change and tell everyone to use the new one.

OK. Will do the necessary fixes.

**Comment by jbemmel** [comment]
Ask someone from Juniper what they would prefer?

I would think to default to the latest - but it’s their call

**Comment by ipspace** [comment]
> Ask someone from Juniper what they would prefer?

Considering their past contributions to the project, I'm inclined to skip this step ;)

> I would think to default to the latest

So we're in perfect agreement 👍
