### ISSUE TITLE
Use prettytable library

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#969]
Instead of creating our own table-printing library in utils.strings, we should use `prettytable`. The existing function should become a wrapper around `prettytable` functions, eventually we could migrate consumers of that function to use native `prettytable` calls.

**Comment by sdktr** [comment]
...or use the [rich library](https://rich.readthedocs.io/en/latest/introduction.html), that has a lot of other nice formatting features besides [tables](https://rich.readthedocs.io/en/latest/tables.html)

**Comment by ipspace** [comment]
> ...or use the [rich library](https://rich.readthedocs.io/en/latest/introduction.html), that has a lot of other nice formatting features besides [tables](https://rich.readthedocs.io/en/latest/tables.html)

Thanks a million. Will definitely go with that library -- it will nicely solve a few other things as well.

**Comment by ipspace** [comment]
Implemented in ac44753479c59b4e6b171fe817fcef4f61f10642

**Comment by ipspace** [comment]
Implemented in ac44753479c59b4e6b171fe817fcef4f61f10642

**Comment by sdktr** [comment]
Pics or it didn't happen 😅
