### ISSUE TITLE
[BUG] fabric.debug renders an error

### ISSUE THREAD

**Issue by sdktr** [ipspace/netlab#974]
### Describe the bug

Debugging fabric plugin with ```fabric.plugin: True``` failes to start netlab

### To Reproduce

Try to show the topology that's added when using fabric plugin, using ```fabric.debug: True```

### Expected behavior

Show the expanded topology file before starting succesfully

### Lab topology

```
plugin: [ fabric ]
fabric.spines: 2
fabric.leafs: 4
fabric.debug: True
```

### Output

```
Errors encountered while processing topology.yml
IncorrectAttr in topology: Incorrect topology attribute debug in topology.fabric
Fatal error in netlab: Cannot proceed beyond this point due to errors, exiting
```

### Version

1.7.0

### Additional context

You can run ```netlab create```, but it has the same error at the end though

**Comment by ipspace** [comment]
Thank you, my fault. Will fix one way or another (= add parameter or fix documentation ;)

**Comment by ipspace** [comment]
The `fabric.debug` parameter was already implemented, so it would be a shame to waste it. Added the parameter to plugin defaults.

Will push out 1.7.0-post1 in a few days, maybe I'll find the willpower to fix some other outstanding issues in the meantime.
