### ISSUE TITLE
[BUG] Fix Cumulus loopback interface name

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#981]
### Describe the bug

#980 introduced calculation of built-in loopback interface name using the `loopback_interface_name` device parameter. Unfortunately, Cumulus Linux uses `lo` not `lo0` for the default loopback, so we need a tweak in the device parameter.

**Comment by ssasso** [comment]
The "problem" is present only if you want to create an additional loopback interface I guess,
(And maybe use as vtep source).

I mean, as per #982 , as far as the system is able to create a link defined with type: loopback, then the rest should be transparent.
The "lo" interface itself is never used on the vxlan config.

**Comment by ipspace** [comment]
> The "problem" is present only if you want to create an additional loopback interface I guess, (And maybe use as vtep source).

Exactly.

> I mean, as per #982 , as far as the system is able to create a link defined with type: loopback, then the rest should be transparent. The "lo" interface itself is never used on the vxlan config/templates for cumulus.

It is -- the VTEP IP address is configured on `lo` in VXLAN template.

Anyway, I stumbled upon another SNAFU -- bridging two VLANs into VXLAN does not work on CL 4.0 we're using. Configurations look OK 🤷‍♂️

**Comment by ipspace** [comment]
Fixed in 040986cb664929994067d8c54fc1a6a16af1ae3b

**Comment by ssasso** [comment]
From what I can see in multiple docs (and unofficial pages) for CL 4, you can specify the source ip directly on each vni interface, and avoid it on the lo interface.

See: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-41/Network-Virtualization/Static-VXLAN-Tunnels/

It seems you have to specify it on the "lo" stanza if you don't want to set it explicitly on all the vni interfaces.

If this is really the case, maybe we can remove any reference of "lo" from the vxlan template.
