### ISSUE TITLE
[BUG] Fix Cumulus VTEP interface

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#982]
### Describe the bug

#980 introduced configurable VTEP. The PR fixed most device templates, but not CL 4.0 template in which the VTEP IP address is tied to `lo` interface. Have to figure out what the correct way is to configure another loopback interface as VTEP source on CL 4.0 and fix the VXLAN template accordingly.

**Comment by ssasso** [comment]
If I am not wrong, Cumulus (together with frr and vyos) does not have to explicitly configure the interface where to bind, but simply the vtep address (which is already done by the current templates)

**Comment by ssasso** [comment]
(and the vxlan.vtep address is correctly set by the module itself)

**Comment by ipspace** [comment]
Close the wrong issue 🤷‍♂️

**Comment by ipspace** [comment]
Looks like the `lo` interface is just a placeholder for a global **ifupdown2** configuration parameter. Used integration test created in 9958a2cb44b206b9bba9faa281c9fb349c8160cf to verify the existing templates work on CL 4.x
