### ISSUE TITLE
[BUG] Arista EOS is failing the vrf-common-ospf integration test

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#991]
Arista EOS redistributes OSPF routes from CE-routers into the VRF BGP table, leaks them into other BGP tables, but does not redistribute those BGP routes back into PE-CE OSPF.

**Comment by jbemmel** [comment]
I am curious about what made you think to close it yesterday, and what's the reason this is being opened again

**Comment by ipspace** [comment]
What makes you think I was thinking at the time? I'm blaming fat fingers. I have no idea why I closed it yesterday (I would have added "stupid me, it works" remark or something), and was a bit surprised when I missed it in the list of open issues.
