### ISSUE TITLE
[BUG] NXOS hostname must be at least 2 characters

### ISSUE THREAD

**Issue by ipspace** [ipspace/netlab#999]
### Describe the bug

Initial device configuration fails on Nexus OS with single-character device names

### Lab topology

```
nodes:
  r:
    device: nxos
```

### Output

```
fatal: [r]: FAILED! => changed=false
  msg: |-
    hostname r
    ERROR: value of property name is out of range:
    switch(config)#
```

**Comment by ssasso** [comment]
Same problem in vyos, where I used this workaround:
https://github.com/ipspace/netlab/blob/f22ebf25a0e328b1ddcbd5ceb41cabf623582e2b/netsim/ansible/templates/initial/vyos.j2#L12
